# CReST: Supplementary Material Assembly

Generates Supplementary Material tables and figures from final aggregate result artifacts and performs structural LaTeX integrity checks.

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# Supplementary material assembly setup

from pathlib import Path
import json
import numpy as np
import pandas as pd

BASE_DIR = Path.cwd()

RESULTS_DIR = BASE_DIR / "results"
SPLITS_DIR = BASE_DIR / "splits"
FIG_DIR = BASE_DIR / "figures"

SUPP_DIR = RESULTS_DIR / "supplementary_material"
SUPP_TABLE_DIR = SUPP_DIR / "tables"
SUPP_FIG_DIR = SUPP_DIR / "figures"

SUPP_TABLE_DIR.mkdir(parents=True, exist_ok=True)
SUPP_FIG_DIR.mkdir(parents=True, exist_ok=True)

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 200)
pd.set_option("display.width", 160)

print("BASE_DIR       :", BASE_DIR)
print("RESULTS_DIR    :", RESULTS_DIR)
print("SPLITS_DIR     :", SPLITS_DIR)
print("SUPP_DIR       :", SUPP_DIR)
print("SUPP_TABLE_DIR :", SUPP_TABLE_DIR)
print("SUPP_FIG_DIR   :", SUPP_FIG_DIR)

BASE_DIR       : PROJECT_ROOT
RESULTS_DIR    : PROJECT_ROOT\results
SPLITS_DIR     : PROJECT_ROOT\splits
SUPP_DIR       : PROJECT_ROOT\results\supplementary_material
SUPP_TABLE_DIR : PROJECT_ROOT\results\supplementary_material\tables
SUPP_FIG_DIR   : PROJECT_ROOT\results\supplementary_material\figures

In [ ]:
# Audit source files required for Supplementary Material

required_files = {

    # S1 - Cross-system split
    "S1_fold_assignment":
        SPLITS_DIR / "country_fold_assignment_7fold.csv",

    "S1_split_protocol":
        SPLITS_DIR / "country_split_protocol_7fold.csv",

    # S2 - Computational reproducibility
    "S2_training_summary":
        RESULTS_DIR / "crest_final_7fold_training_summary.csv",

    "S2_training_time":
        RESULTS_DIR / "crest_final_7fold_training_time_audit.csv",

    "S2_inference_time":
        RESULTS_DIR / "crest_final_7fold_inference_time_audit.csv",

    "S2_parameter_count":
        RESULTS_DIR / "crest_final_parameter_count_audit.csv",

    "S2_environment":
        RESULTS_DIR / "crest_hardware_environment_audit.csv",

    # S3 - Assessment-design robustness
    "S3_design_progression":
        RESULTS_DIR / "fold0_design_leakage_progression.csv",

    "S3_design_signal_retention":
        RESULTS_DIR / "fold0_design_calibration_signal_retention.csv",

    "S3_final_nuisance":
        RESULTS_DIR / "crest_final_crosssystem_nuisance_summary.csv",

    # S4 - Domain/process representation results
    "S4_domain_summary":
        RESULTS_DIR / "crest_domain_increment_summary.csv",

    "S4_process_summary":
        RESULTS_DIR / "crest_process_increment_summary.csv",

    # S5 - Context / population analyses
    "S5_population_contrasts":
        RESULTS_DIR / "survey_weighted_population" /
        "crest_population_context_contrasts_summary.csv",

    "S5_adjusted_min30":
        RESULTS_DIR / "survey_weighted_population" /
        "crest_adjusted_associations_summary_min30.csv",

    "S5_adjusted_min50":
        RESULTS_DIR / "survey_weighted_population" /
        "crest_adjusted_associations_summary_min50.csv",

    # S6 - Official PISA alignment
    "S6_pisa_alignment":
        RESULTS_DIR / "survey_weighted_population" /
        "crest_convergent_validity_pisa_ct_summary.csv",

    # S7 - Profile structure / clustering
    "S7_cluster_metrics":
        RESULTS_DIR / "crosssystem_profile_stability" /
        "crest_profile_cluster_pv_fit_metrics.csv",

    "S7_centroids":
        RESULTS_DIR / "crosssystem_profile_stability" /
        "crest_k2_centroid_summary.csv",

    "S7_axis_stability":
        RESULTS_DIR / "crosssystem_profile_stability" /
        "crest_continuous_profile_axes_63system_summary.csv",

    # S8 - Final sensitivity
    "S8_sensitivity":
        RESULTS_DIR / "final_sensitivity_robustness" /
        "crest_final_sensitivity_findings_LOCKED.json",
}

audit_rows = []

for key, path in required_files.items():
    audit_rows.append({
        "source_id": key,
        "exists": path.exists(),
        "file": str(path.relative_to(BASE_DIR)) if path.exists() else str(path),
        "size_kb": round(path.stat().st_size / 1024, 2) if path.exists() else np.nan
    })

audit_df = pd.DataFrame(audit_rows)

display(audit_df)

print("\n" + "=" * 100)

missing = audit_df.loc[~audit_df["exists"]]

if len(missing) == 0:
    print("PASS: All planned Supplementary source files are available.")
else:
    print(f"WARNING: {len(missing)} planned source file(s) are missing:")
    display(missing)

                     source_id  exists                                               file  size_kb
0           S1_fold_assignment    True           splits\country_fold_assignment_7fold.csv     1.02
1            S1_split_protocol    True            splits\country_split_protocol_7fold.csv     0.39
2          S2_training_summary    True     results\crest_final_7fold_training_summary.csv     1.11
3             S2_training_time    True  results\crest_final_7fold_training_time_audit.csv     1.11
4            S2_inference_time    True  results\crest_final_7fold_inference_time_audit...     0.78
5           S2_parameter_count    True      results\crest_final_parameter_count_audit.csv     0.37
6               S2_environment    True       results\crest_hardware_environment_audit.csv     0.40
7        S3_design_progression    True       results\fold0_design_leakage_progression.csv     0.13
8   S3_design_signal_retention    True  results\fold0_design_calibration_signal_retent...     0.44
9            S3_final_nuisance    True  results\crest_final_crosssystem_nuisance_summa...     1.08
10           S4_domain_summary    True         results\crest_domain_increment_summary.csv     1.65
11          S4_process_summary    True        results\crest_process_increment_summary.csv     1.00
12     S5_population_contrasts    True  results\survey_weighted_population\crest_popul...     1.09
13           S5_adjusted_min30    True  results\survey_weighted_population\crest_adjus...     1.30
14           S5_adjusted_min50    True  results\survey_weighted_population\crest_adjus...     1.30
15           S6_pisa_alignment    True  results\survey_weighted_population\crest_conve...     0.33
16          S7_cluster_metrics    True  results\crosssystem_profile_stability\crest_pr...     3.25
17                S7_centroids    True  results\crosssystem_profile_stability\crest_k2...     0.37
18           S7_axis_stability    True  results\crosssystem_profile_stability\crest_co...    10.69
19              S8_sensitivity    True  results\final_sensitivity_robustness\crest_fin...     2.30

====================================================================================================
PASS: All planned Supplementary source files are available.

In [ ]:
# Inspect locked seven-fold split files

fold_assignment_path = SPLITS_DIR / "country_fold_assignment_7fold.csv"
split_protocol_path = SPLITS_DIR / "country_split_protocol_7fold.csv"

fold_assignment = pd.read_csv(fold_assignment_path)
split_protocol = pd.read_csv(split_protocol_path)

print("=" * 100)
print("A. COUNTRY / EDUCATION-SYSTEM FOLD ASSIGNMENT")
print("=" * 100)

print("Shape:", fold_assignment.shape)
print("Columns:", fold_assignment.columns.tolist())
display(fold_assignment)

print("\n" + "=" * 100)
print("B. SEVEN-FOLD SPLIT PROTOCOL")
print("=" * 100)

print("Shape:", split_protocol.shape)
print("Columns:", split_protocol.columns.tolist())
display(split_protocol)

In [ ]:
# Build Supplementary Table S1:
# Seven-fold education-system assignment and sample sizes

import pandas as pd
from pathlib import Path

# Load locked split files

fold_assignment = pd.read_csv(
    SPLITS_DIR / "country_fold_assignment_7fold.csv"
)

split_protocol = pd.read_csv(
    SPLITS_DIR / "country_split_protocol_7fold.csv"
)

# Build human-readable system lists

rows = []

for _, r in split_protocol.iterrows():

    outer_fold = int(r["outer_fold"])
    test_fold = int(r["test_country_fold"])
    val_fold = int(r["validation_country_fold"])

    test_systems = sorted(
        fold_assignment.loc[
            fold_assignment["country_fold"] == test_fold,
            "CNT"
        ].tolist()
    )

    val_systems = sorted(
        fold_assignment.loc[
            fold_assignment["country_fold"] == val_fold,
            "CNT"
        ].tolist()
    )

    # Training systems = all systems not in validation or test folds
    train_systems = sorted(
        fold_assignment.loc[
            ~fold_assignment["country_fold"].isin(
                [test_fold, val_fold]
            ),
            "CNT"
        ].tolist()
    )

    assert len(train_systems) == 45
    assert len(val_systems) == 9
    assert len(test_systems) == 9

    rows.append({
        "Outer fold": outer_fold,
        "Training systems": 45,
        "Validation systems": ", ".join(val_systems),
        "Test systems": ", ".join(test_systems),
        "Train students": int(r["n_train_students"]),
        "Validation students": int(r["n_validation_students"]),
        "Test students": int(r["n_test_students"]),
    })

table_s1 = pd.DataFrame(rows)

print("=" * 120)
print("SUPPLEMENTARY TABLE S1")
print("=" * 120)

display(table_s1)

# Global integrity checks

all_test_systems = []
all_validation_systems = []

for _, r in split_protocol.iterrows():

    test_fold = int(r["test_country_fold"])
    val_fold = int(r["validation_country_fold"])

    all_test_systems.extend(
        fold_assignment.loc[
            fold_assignment["country_fold"] == test_fold,
            "CNT"
        ].tolist()
    )

    all_validation_systems.extend(
        fold_assignment.loc[
            fold_assignment["country_fold"] == val_fold,
            "CNT"
        ].tolist()
    )

print("\n" + "=" * 120)
print("INTEGRITY CHECKS")
print("=" * 120)

print("Unique systems in dataset:",
      fold_assignment["CNT"].nunique())

print("Total test assignments:",
      len(all_test_systems))

print("Unique test systems:",
      len(set(all_test_systems)))

print("Every system exactly once as test:",
      len(all_test_systems) == 63
      and len(set(all_test_systems)) == 63)

print("Total validation assignments:",
      len(all_validation_systems))

print("Unique validation systems:",
      len(set(all_validation_systems)))

print("Every system exactly once as validation:",
      len(all_validation_systems) == 63
      and len(set(all_validation_systems)) == 63)

# Save CSV

csv_path = SUPP_TABLE_DIR / \
    "Table_S1_seven_fold_system_assignment.csv"

table_s1.to_csv(csv_path, index=False)

print("\nSaved CSV:")
print(csv_path)

# Generate final two-panel Supplementary Table S1

latex_lines = [
    r"\\begin{table*}[t]",
    r"\\caption{Seven-fold education-system assignment used for confirmatory cross-system evaluation.}",
    r"\\label{tab:supp_split_assignment}",
    r"\\centering",
    r"\\renewcommand{\\arraystretch}{1.15}",
    "",
    r"\\textbf{Panel A. Validation and test education systems}",
    r"\\medskip",
    r"\\resizebox{\\textwidth}{!}{%",
    r"\\begin{tabular}{@{}cll@{}}",
    r"\\toprule",
    r"\\textbf{Outer fold} & \\textbf{Validation systems} & \\textbf{Test systems} \\\\",
    r"\\midrule",
]

for _, r in table_s1.iterrows():
    latex_lines.append(
        f"{int(r['Outer fold'])} & "
        f"{r['Validation systems']} & "
        f"{r['Test systems']} \\\\"
    )

latex_lines += [
    r"\\bottomrule",
    r"\\end{tabular}%",
    r"}",
    r"\\vspace{0.9em}",
    "",
    r"\\textbf{Panel B. Sample sizes by outer fold}",
    r"\\medskip",
    r"\\small",
    r"\\begin{tabular}{@{}crrr@{}}",
    r"\\toprule",
    r"\\textbf{Outer fold} & \\textbf{Training $N$} & \\textbf{Validation $N$} & \\textbf{Test $N$} \\\\",
    r"\\midrule",
]

for _, r in table_s1.iterrows():
    latex_lines.append(
        f"{int(r['Outer fold'])} & "
        f"{int(r['Train students']):,} & "
        f"{int(r['Validation students']):,} & "
        f"{int(r['Test students']):,} \\\\"
    )

latex_lines += [
    r"\\bottomrule",
    r"\\end{tabular}",
    r"\\begin{flushleft}",
    r"\\footnotesize",
    r"\\textit{Note.} System labels are the three-letter identifiers used in the PISA 2022 public-use files. "
    r"For each outer fold, the listed test systems were completely unseen during model development, "
    r"the listed validation systems were used for model selection, and the remaining 45 education systems "
    r"formed the training set. Each of the 63 education systems served exactly once as an unseen test system "
    r"and exactly once as a validation system.",
    r"\\end{flushleft}",
    r"\\end{table*}",
]

latex_text = "\n".join(latex_lines)
tex_path = SUPP_TABLE_DIR / "Table_S1_seven_fold_system_assignment.tex"
tex_path.write_text(latex_text, encoding="utf-8")

print("Saved:", tex_path)

In [ ]:
# Build Supplementary Table S2
# Fold-level computational and reproducibility audit
# Parameter count is audited separately.

import pandas as pd

# Load locked audit files

training_summary = pd.read_csv(
    RESULTS_DIR / "crest_final_7fold_training_summary.csv"
)

training_time = pd.read_csv(
    RESULTS_DIR / "crest_final_7fold_training_time_audit.csv"
)

inference_time = pd.read_csv(
    RESULTS_DIR / "crest_final_7fold_inference_time_audit.csv"
)

# Merge fold-level information

s2 = (
    training_summary[
        [
            "outer_fold",
            "best_epoch",
            "best_validation_reconstruction",
            "epochs_run",
        ]
    ]
    .merge(
        training_time[
            [
                "outer_fold",
                "total_training_hours",
                "mean_epoch_seconds",
            ]
        ],
        on="outer_fold",
        how="left",
        validate="one_to_one"
    )
    .merge(
        inference_time[
            [
                "outer_fold",
                "checkpoint_epoch",
                "n_students",
                "latent_inference_seconds",
                "students_per_second",
                "milliseconds_per_student",
                "model_updated_on_test",
            ]
        ],
        on="outer_fold",
        how="left",
        validate="one_to_one"
    )
)

# Integrity checks

assert len(s2) == 7
assert not s2.isna().any().any(), "Missing values appeared after merge."
assert (s2["best_epoch"] == s2["checkpoint_epoch"]).all()
assert (~s2["model_updated_on_test"]).all()

# Publication-oriented table

table_s2 = pd.DataFrame({
    "Outer fold": s2["outer_fold"].astype(int),
    "Selected epoch": s2["best_epoch"].astype(int),
    "Epochs run": s2["epochs_run"].astype(int),
    "Validation reconstruction":
        s2["best_validation_reconstruction"],
    "Training time (h)":
        s2["total_training_hours"],
    "Mean epoch time (min)":
        s2["mean_epoch_seconds"] / 60,
    "Test N":
        s2["n_students"].astype(int),
    "Inference (ms/student)":
        s2["milliseconds_per_student"],
    "Throughput (students/s)":
        s2["students_per_second"],
})

print("=" * 120)
print("SUPPLEMENTARY TABLE S2")
print("=" * 120)

display(
    table_s2.round({
        "Validation reconstruction": 4,
        "Training time (h)": 3,
        "Mean epoch time (min)": 2,
        "Inference (ms/student)": 4,
        "Throughput (students/s)": 1,
    })
)

# Aggregate statistics

total_epochs = int(s2["epochs_run"].sum())
total_training_hours = s2["total_training_hours"].sum()

total_test_students = int(s2["n_students"].sum())
total_inference_seconds = s2["latent_inference_seconds"].sum()

pooled_ms_per_student = (
    total_inference_seconds / total_test_students
) * 1000

pooled_throughput = (
    total_test_students / total_inference_seconds
)

weighted_mean_epoch_seconds = (
    (s2["mean_epoch_seconds"] * s2["epochs_run"]).sum()
    / total_epochs
)

print("\n" + "=" * 120)
print("INTEGRITY / AGGREGATE CHECKS")
print("=" * 120)

print(
    "Selected epoch equals inference checkpoint epoch in all folds:",
    (s2["best_epoch"] == s2["checkpoint_epoch"]).all()
)

print(
    "All confirmatory test evaluations model-frozen:",
    (~s2["model_updated_on_test"]).all()
)

print(f"Total epochs executed: {total_epochs}")
print(f"Total final training time: {total_training_hours:.3f} h")
print(
    f"Mean epoch time: "
    f"{weighted_mean_epoch_seconds / 60:.2f} min"
)
print(f"Total held-out students: {total_test_students:,}")
print(
    f"Pooled latent inference: "
    f"{pooled_ms_per_student:.4f} ms/student"
)
print(
    f"Pooled throughput: "
    f"{pooled_throughput:.2f} students/s"
)

# Save CSV

csv_path = (
    SUPP_TABLE_DIR /
    "Table_S2_fold_level_computational_audit.csv"
)

table_s2.to_csv(csv_path, index=False)

print("\nSaved CSV:")
print(csv_path)

# Generate LaTeX

latex_lines = []

latex_lines.append(r"\begin{table*}[t]")
latex_lines.append(
    r"\caption{Fold-level computational and reproducibility "
    r"characteristics of the locked CReST confirmatory training "
    r"and inference protocol.}"
)
latex_lines.append(r"\label{tab:supp_computational_audit}")
latex_lines.append(r"\centering")
latex_lines.append(r"\scriptsize")
latex_lines.append(r"\renewcommand{\arraystretch}{1.10}")
latex_lines.append(r"\setlength{\tabcolsep}{4pt}")
latex_lines.append("")
latex_lines.append(r"\begin{tabular}{@{}ccccccccc@{}}")
latex_lines.append(r"\toprule")
latex_lines.append(
    r"\textbf{Fold} & "
    r"\textbf{Selected} & "
    r"\textbf{Epochs} & "
    r"\textbf{Validation} & "
    r"\textbf{Training} & "
    r"\textbf{Epoch time} & "
    r"\textbf{Test} & "
    r"\textbf{Inference} & "
    r"\textbf{Throughput} \\"
)
latex_lines.append(
    r" & "
    r"\textbf{epoch} & "
    r"\textbf{run} & "
    r"\textbf{reconstruction} & "
    r"\textbf{time (h)} & "
    r"\textbf{(min)} & "
    r"\textbf{$N$} & "
    r"\textbf{(ms/student)} & "
    r"\textbf{(students/s)} \\"
)
latex_lines.append(r"\midrule")

for _, r in table_s2.iterrows():
    latex_lines.append(
        f"{int(r['Outer fold'])} & "
        f"{int(r['Selected epoch'])} & "
        f"{int(r['Epochs run'])} & "
        f"{r['Validation reconstruction']:.4f} & "
        f"{r['Training time (h)']:.3f} & "
        f"{r['Mean epoch time (min)']:.2f} & "
        f"{int(r['Test N']):,} & "
        f"{r['Inference (ms/student)']:.4f} & "
        f"{r['Throughput (students/s)']:.1f} \\\\"
    )

latex_lines.append(r"\midrule")

latex_lines.append(
    f"\\multicolumn{{3}}{{l}}{{\\textbf{{Overall}}}} & "
    f"-- & "
    f"{total_training_hours:.2f} & "
    f"{weighted_mean_epoch_seconds / 60:.2f} & "
    f"{total_test_students:,} & "
    f"{pooled_ms_per_student:.3f} & "
    f"{pooled_throughput:.1f} \\\\"
)

latex_lines.append(r"\bottomrule")
latex_lines.append(r"\end{tabular}")
latex_lines.append("")
latex_lines.append(
    r"\begin{flushleft}"
    r"\footnotesize "
    r"\textit{Note.} Training time is the sum of the recorded "
    r"wall-clock epoch durations for all epochs actually executed "
    r"in each outer fold. Inference refers to frozen latent "
    r"representation extraction on the corresponding completely "
    r"held-out test systems. All training and confirmatory inference "
    r"were conducted on the same CPU-only workstation "
    r"(Intel Core i7-6700HQ, 2.60\,GHz; 4 physical / 8 logical "
    r"cores; approximately 24\,GB RAM), with no CUDA-enabled GPU. "
    r"No model parameters were updated during confirmatory test "
    r"evaluation."
    r"\end{flushleft}"
)

latex_lines.append(r"\end{table*}")

latex_text = "\n".join(latex_lines)

tex_path = (
    SUPP_TABLE_DIR /
    "Table_S2_fold_level_computational_audit.tex"
)

tex_path.write_text(latex_text, encoding="utf-8")

print("\nSaved LaTeX:")
print(tex_path)

print("\n" + "=" * 120)
print("LATEX PREVIEW")
print("=" * 120)
print(latex_text)

========================================================================================================================
SUPPLEMENTARY TABLE S2
========================================================================================================================

,Outer fold,Selected epoch,Epochs run,Validation reconstruction,Training time (h),Mean epoch time (min),Test N,Inference (ms/student),Throughput (students/s)
0,0,18,20,1.4023,5.343,16.03,21649,1.2899,775.3
1,1,19,20,1.4475,5.311,15.93,20949,1.2132,824.3
2,2,19,20,1.4674,5.400,16.20,20769,1.2321,811.6
3,3,11,15,1.4118,4.018,16.07,20324,1.2845,778.5
4,4,20,20,1.4406,5.270,15.81,19460,1.2143,823.5
5,5,6,10,1.4599,2.633,15.80,19694,1.3230,755.9
6,6,17,20,1.4631,5.184,15.55,19719,1.2687,788.2

========================================================================================================================
INTEGRITY / AGGREGATE CHECKS
========================================================================================================================
Selected epoch equals inference checkpoint epoch in all folds: True
All confirmatory test evaluations model-frozen: True
Total epochs executed: 125
Total final training time: 33.159 h
Mean epoch time: 15.92 min
Total held-out students: 142,564
Pooled latent inference: 1.2607 ms/student
Pooled throughput: 793.18 students/s

Saved CSV:
PROJECT_ROOT\results\supplementary_material\tables\Table_S2_fold_level_computational_audit.csv

Saved LaTeX:
PROJECT_ROOT\results\supplementary_material\tables\Table_S2_fold_level_computational_audit.tex

========================================================================================================================
LATEX PREVIEW
========================================================================================================================
\begin{table*}[t]
\caption{Fold-level computational and reproducibility characteristics of the locked CReST confirmatory training and inference protocol.}
\label{tab:supp_computational_audit}
\centering
\scriptsize
\renewcommand{\arraystretch}{1.10}
\setlength{\tabcolsep}{4pt}

\begin{tabular}{@{}ccccccccc@{}}
\toprule
\textbf{Fold} & \textbf{Selected} & \textbf{Epochs} & \textbf{Validation} & \textbf{Training} & \textbf{Epoch time} & \textbf{Test} & \textbf{Inference} & \textbf{Throughput} \\
 & \textbf{epoch} & \textbf{run} & \textbf{reconstruction} & \textbf{time (h)} & \textbf{(min)} & \textbf{$N$} & \textbf{(ms/student)} & \textbf{(students/s)} \\
\midrule
0 & 18 & 20 & 1.4023 & 5.343 & 16.03 & 21,649 & 1.2899 & 775.3 \\
1 & 19 & 20 & 1.4475 & 5.311 & 15.93 & 20,949 & 1.2132 & 824.3 \\
2 & 19 & 20 & 1.4674 & 5.400 & 16.20 & 20,769 & 1.2321 & 811.6 \\
3 & 11 & 15 & 1.4118 & 4.018 & 16.07 & 20,324 & 1.2845 & 778.5 \\
4 & 20 & 20 & 1.4406 & 5.270 & 15.81 & 19,460 & 1.2143 & 823.5 \\
5 & 6 & 10 & 1.4599 & 2.633 & 15.80 & 19,694 & 1.3230 & 755.9 \\
6 & 17 & 20 & 1.4631 & 5.184 & 15.55 & 19,719 & 1.2687 & 788.2 \\
\midrule
\multicolumn{3}{l}{\textbf{Overall}} & -- & 33.16 & 15.92 & 142,564 & 1.261 & 793.2 \\
\bottomrule
\end{tabular}

\begin{flushleft}\footnotesize \textit{Note.} Training time is the sum of the recorded wall-clock epoch durations for all epochs actually executed in each outer fold. Inference refers to frozen latent representation extraction on the corresponding completely held-out test systems. All training and confirmatory inference were conducted on the same CPU-only workstation (Intel Core i7-6700HQ, 2.60\,GHz; 4 physical / 8 logical cores; approximately 24\,GB RAM), with no CUDA-enabled GPU. No model parameters were updated during confirmatory test evaluation.\end{flushleft}
\end{table*}

In [ ]:
# Diagnose parameter-count audit discrepancy

parameter_audit = pd.read_csv(
    RESULTS_DIR / "crest_final_parameter_count_audit.csv"
)

cols = [
    "outer_fold",
    "checkpoint_epoch",
    "state_dict_tensors",
    "state_dict_numel",
    "optimizer_parameter_tensors",
    "optimizer_parameter_numel",
    "counts_match",
]

display(parameter_audit[cols])

parameter_audit["difference"] = (
    parameter_audit["state_dict_numel"]
    - parameter_audit["optimizer_parameter_numel"]
)

print("\nDifferences:")
display(
    parameter_audit[
        [
            "outer_fold",
            "state_dict_numel",
            "optimizer_parameter_numel",
            "difference",
            "counts_match",
        ]
    ]
)

print(
    "\nUnique state_dict counts:",
    parameter_audit["state_dict_numel"].unique()
)

print(
    "Unique optimizer-derived counts:",
    parameter_audit["optimizer_parameter_numel"].unique()
)

   outer_fold  checkpoint_epoch  state_dict_tensors  state_dict_numel  optimizer_parameter_tensors  optimizer_parameter_numel  counts_match
0           0                18                 216           1578024                          208                    1577398         False
1           1                19                 216           1578024                          208                    1577398         False
2           2                19                 216           1578024                          208                    1577398         False
3           3                11                 216           1578024                          208                    1577398         False
4           4                20                 216           1578024                          208                    1577398         False
5           5                 6                 216           1578024                          208                    1577398         False
6           6                17                 216           1578024                          208                    1577398         False

Differences:

   outer_fold  state_dict_numel  optimizer_parameter_numel  difference  counts_match
0           0           1578024                    1577398         626         False
1           1           1578024                    1577398         626         False
2           2           1578024                    1577398         626         False
3           3           1578024                    1577398         626         False
4           4           1578024                    1577398         626         False
5           5           1578024                    1577398         626         False
6           6           1578024                    1577398         626         False

Unique state_dict counts: [1578024]
Unique optimizer-derived counts: [1577398]

In [ ]:
# Identify state_dict tensors not represented in optimizer state

from pathlib import Path
from collections import Counter, defaultdict
import torch

BASE_DIR = Path.cwd()
CKPT_PATH = (
    BASE_DIR
    / "checkpoints"
    / "final_7fold"
    / "fold_0"
    / "crest_final_best.pt"
)

ckpt = torch.load(
    CKPT_PATH,
    map_location="cpu",
    weights_only=False
)

model_state = ckpt["model_state_dict"]
optimizer_state = ckpt["optimizer_state_dict"]

# Collect state_dict tensor signatures

state_entries = []

for key, tensor in model_state.items():
    if torch.is_tensor(tensor):
        state_entries.append({
            "key": key,
            "shape": tuple(tensor.shape),
            "numel": tensor.numel(),
            "dtype": str(tensor.dtype),
        })

# Collect optimizer parameter signatures from exp_avg

opt_shapes = []

for state in optimizer_state["state"].values():
    if "exp_avg" in state:
        t = state["exp_avg"]
        opt_shapes.append(
            (tuple(t.shape), t.numel())
        )

opt_counter = Counter(opt_shapes)

# Match state_dict tensors against optimizer tensor signatures
# using a multiset comparison

matched_counter = Counter()
candidate_nonoptimised = []

for entry in state_entries:

    sig = (entry["shape"], entry["numel"])

    if matched_counter[sig] < opt_counter[sig]:
        matched_counter[sig] += 1
    else:
        candidate_nonoptimised.append(entry)

print("=" * 100)
print("CANDIDATE STATE_DICT TENSORS NOT REPRESENTED IN OPTIMIZER STATE")
print("=" * 100)

total_extra = 0

for entry in candidate_nonoptimised:
    print(
        f"{entry['key']:<70} "
        f"shape={str(entry['shape']):<20} "
        f"numel={entry['numel']:<8} "
        f"dtype={entry['dtype']}"
    )
    total_extra += entry["numel"]

print("\n" + "=" * 100)
print("SUMMARY")
print("=" * 100)

print("Candidate tensors :", len(candidate_nonoptimised))
print("Candidate elements:", total_extra)
print("Expected tensors  :", 8)
print("Expected elements :", 626)

print(
    "\nExact match to audit discrepancy:",
    len(candidate_nonoptimised) == 8
    and total_extra == 626
)

====================================================================================================
CANDIDATE STATE_DICT TENSORS NOT REPRESENTED IN OPTIMIZER STATE
====================================================================================================
item_domain_ids                                                        shape=(32,)                numel=32       dtype=torch.int64
item_ideation_ids                                                      shape=(32,)                numel=32       dtype=torch.int64
general_builder.item_ideation_ids                                      shape=(32,)                numel=32       dtype=torch.int64
general_builder.credit_item_mean                                       shape=(32,)                numel=32       dtype=torch.float32
general_builder.behaviour_item_rates                                   shape=(32, 3)              numel=96       dtype=torch.float32
general_builder.process_item_mean                                      shape=(32, 3)              numel=96       dtype=torch.float32
general_builder.process_item_std                                       shape=(32, 3)              numel=96       dtype=torch.float32
general_builder.signature_token_profiles                               shape=(10, 3, 7)           numel=210      dtype=torch.float32

====================================================================================================
SUMMARY
====================================================================================================
Candidate tensors : 8
Candidate elements: 626
Expected tensors  : 8
Expected elements : 626

Exact match to audit discrepancy: True

In [ ]:
# Save refined trainable-parameter audit

import json
from pathlib import Path

buffer_summary = {
    "trainable_parameters": 1_577_398,
    "non_trainable_state_elements": 626,
    "total_state_dict_elements": 1_578_024,
    "state_dict_tensor_count": 216,
    "optimizer_parameter_tensor_count": 208,
    "non_trainable_tensors": [
        {
            "name": "item_domain_ids",
            "shape": [32],
            "numel": 32,
            "role": "fixed item-domain identifiers",
        },
        {
            "name": "item_ideation_ids",
            "shape": [32],
            "numel": 32,
            "role": "fixed item-ideation identifiers",
        },
        {
            "name": "general_builder.item_ideation_ids",
            "shape": [32],
            "numel": 32,
            "role": "fixed general-branch ideation identifiers",
        },
        {
            "name": "general_builder.credit_item_mean",
            "shape": [32],
            "numel": 32,
            "role": "training-derived credit calibration statistics",
        },
        {
            "name": "general_builder.behaviour_item_rates",
            "shape": [32, 3],
            "numel": 96,
            "role": "training-derived behavioural calibration statistics",
        },
        {
            "name": "general_builder.process_item_mean",
            "shape": [32, 3],
            "numel": 96,
            "role": "training-derived process-feature means",
        },
        {
            "name": "general_builder.process_item_std",
            "shape": [32, 3],
            "numel": 96,
            "role": "training-derived process-feature standard deviations",
        },
        {
            "name": "general_builder.signature_token_profiles",
            "shape": [10, 3, 7],
            "numel": 210,
            "role": "training-derived assessment-design calibration profiles",
        },
    ],
    "verification": (
        "The 626-element difference between the model state_dict and "
        "optimizer-derived parameter count is fully explained by eight "
        "fixed registered tensors. The verified trainable/optimised "
        "parameter count is therefore 1,577,398."
    ),
}

out_path = (
    RESULTS_DIR /
    "crest_final_parameter_count_refined_audit.json"
)

with open(out_path, "w", encoding="utf-8") as f:
    json.dump(buffer_summary, f, indent=2)

print(json.dumps(buffer_summary, indent=2))
print("\nSaved:")
print(out_path)

{
  "trainable_parameters": 1577398,
  "non_trainable_state_elements": 626,
  "total_state_dict_elements": 1578024,
  "state_dict_tensor_count": 216,
  "optimizer_parameter_tensor_count": 208,
  "non_trainable_tensors": [
    {
      "name": "item_domain_ids",
      "shape": [
        32
      ],
      "numel": 32,
      "role": "fixed item-domain identifiers"
    },
    {
      "name": "item_ideation_ids",
      "shape": [
        32
      ],
      "numel": 32,
      "role": "fixed item-ideation identifiers"
    },
    {
      "name": "general_builder.item_ideation_ids",
      "shape": [
        32
      ],
      "numel": 32,
      "role": "fixed general-branch ideation identifiers"
    },
    {
      "name": "general_builder.credit_item_mean",
      "shape": [
        32
      ],
      "numel": 32,
      "role": "training-derived credit calibration statistics"
    },
    {
      "name": "general_builder.behaviour_item_rates",
      "shape": [
        32,
        3
      ],
      "numel": 96,
      "role": "training-derived behavioural calibration statistics"
    },
    {
      "name": "general_builder.process_item_mean",
      "shape": [
        32,
        3
      ],
      "numel": 96,
      "role": "training-derived process-feature means"
    },
    {
      "name": "general_builder.process_item_std",
      "shape": [
        32,
        3
      ],
      "numel": 96,
      "role": "training-derived process-feature standard deviations"
    },
    {
      "name": "general_builder.signature_token_profiles",
      "shape": [
        10,
        3,
        7
      ],
      "numel": 210,
      "role": "training-derived assessment-design calibration profiles"
    }
  ],
  "verification": "The 626-element difference between the model state_dict and optimizer-derived parameter count is fully explained by eight fixed registered tensors. The verified trainable/optimised parameter count is therefore 1,577,398."
}

Saved:
PROJECT_ROOT\results\crest_final_parameter_count_refined_audit.json

In [ ]:
# Inspect assessment-design robustness source files

design_progression = pd.read_csv(
    RESULTS_DIR / "fold0_design_leakage_progression.csv"
)

signal_retention = pd.read_csv(
    RESULTS_DIR / "fold0_design_calibration_signal_retention.csv"
)

final_nuisance = pd.read_csv(
    RESULTS_DIR / "crest_final_crosssystem_nuisance_summary.csv"
)

print("=" * 110)
print("A. DESIGN-LEAKAGE PROGRESSION")
print("=" * 110)

print("Shape:", design_progression.shape)
print("Columns:", design_progression.columns.tolist())
display(design_progression)


print("\n" + "=" * 110)
print("B. DESIGN-CALIBRATION SIGNAL RETENTION")
print("=" * 110)

print("Shape:", signal_retention.shape)
print("Columns:", signal_retention.columns.tolist())
display(signal_retention)


print("\n" + "=" * 110)
print("C. FINAL CROSS-SYSTEM NUISANCE SUMMARY")
print("=" * 110)

print("Shape:", final_nuisance.shape)
print("Columns:", final_nuisance.columns.tolist())
display(final_nuisance)

In [ ]:
# Build Supplementary Table S3:
# Development-stage assessment-design calibration and creative-signal retention

import pandas as pd
import numpy as np

design_progression = pd.read_csv(
    RESULTS_DIR / "fold0_design_leakage_progression.csv"
)

signal_retention = pd.read_csv(
    RESULTS_DIR / "fold0_design_calibration_signal_retention.csv"
)

# Panel A: design-leakage progression

panel_a = design_progression.copy()

label_map = {
    "raw_mask_free": "Raw mask-free representation",
    "item_residualized": "Item-residualised representation",
    "country_equal_design_calibrated":
        "Country-equal design-calibrated representation",
}

panel_a["Representation stage"] = (
    panel_a["representation"]
    .map(label_map)
    .fillna(panel_a["representation"])
)

panel_a = panel_a[
    [
        "Representation stage",
        "balanced_accuracy",
    ]
].rename(
    columns={
        "balanced_accuracy": "Design-leakage balanced accuracy"
    }
)

# Relative reduction from raw mask-free baseline
raw_ba = float(
    design_progression.loc[
        design_progression["representation"] == "raw_mask_free",
        "balanced_accuracy"
    ].iloc[0]
)

panel_a["Reduction vs. raw (%)"] = (
    (raw_ba - panel_a["Design-leakage balanced accuracy"])
    / raw_ba
    * 100
)

# Panel B: hidden-target creative-signal retention

panel_b = signal_retention.copy()

rep_map = {
    "item_residualized": "Item-residualised",
    "design_calibrated": "Design-calibrated",
}

direction_map = {
    "A_to_B": r"A$\rightarrow$B",
    "B_to_A": r"B$\rightarrow$A",
}

panel_b["Direction"] = (
    panel_b["direction"]
    .map(direction_map)
    .fillna(panel_b["direction"])
)

panel_b["Representation"] = (
    panel_b["representation"]
    .map(rep_map)
    .fillna(panel_b["representation"])
)

panel_b = panel_b[
    [
        "Direction",
        "Representation",
        "n_train",
        "n_validation",
        "R2",
        "MAE",
        "Spearman_rho",
    ]
].rename(
    columns={
        "n_train": "Train N",
        "n_validation": "Validation N",
        "R2": "R2",
        "MAE": "MAE",
        "Spearman_rho": "Spearman rho",
    }
)

# Summary checks

rho_summary = (
    signal_retention
    .groupby("representation", as_index=False)["Spearman_rho"]
    .mean()
)

rho_resid = float(
    rho_summary.loc[
        rho_summary["representation"] == "item_residualized",
        "Spearman_rho"
    ].iloc[0]
)

rho_cal = float(
    rho_summary.loc[
        rho_summary["representation"] == "design_calibrated",
        "Spearman_rho"
    ].iloc[0]
)

print("=" * 120)
print("SUPPLEMENTARY TABLE S3 - PANEL A")
print("=" * 120)
display(panel_a.round(4))

print("\n" + "=" * 120)
print("SUPPLEMENTARY TABLE S3 - PANEL B")
print("=" * 120)
display(
    panel_b.round({
        "R2": 4,
        "MAE": 4,
        "Spearman rho": 4,
    })
)

print("\n" + "=" * 120)
print("SUMMARY")
print("=" * 120)

final_ba = float(
    panel_a.iloc[-1]["Design-leakage balanced accuracy"]
)

print(f"Raw design-leakage BA                : {raw_ba:.6f}")
print(f"Final calibrated design-leakage BA   : {final_ba:.6f}")
print(
    f"Relative reduction                   : "
    f"{(raw_ba-final_ba)/raw_ba*100:.2f}%"
)
print(
    f"Mean residualised hidden-target rho  : {rho_resid:.6f}"
)
print(
    f"Mean calibrated hidden-target rho    : {rho_cal:.6f}"
)
print(
    f"Change in mean hidden-target rho     : "
    f"{rho_cal-rho_resid:+.6f}"
)

# Save source tables

panel_a_path = (
    SUPP_TABLE_DIR /
    "Table_S3A_design_calibration_progression.csv"
)

panel_b_path = (
    SUPP_TABLE_DIR /
    "Table_S3B_design_calibration_signal_retention.csv"
)

panel_a.to_csv(panel_a_path, index=False)
panel_b.to_csv(panel_b_path, index=False)

# Generate LaTeX table with two panels

latex_lines = []

latex_lines.append(r"\begin{table*}[t]")
latex_lines.append(
    r"\caption{Development-stage assessment-design calibration and "
    r"hidden-target creative-signal retention. Panel A reports the "
    r"progressive reduction in design-leakage probe performance during "
    r"Fold-0 architecture development. Panel B verifies that the final "
    r"design-calibration step did not materially reduce hidden-target "
    r"creative-signal transfer on the validation systems.}"
)
latex_lines.append(r"\label{tab:supp_design_calibration}")
latex_lines.append(r"\centering")
latex_lines.append(r"\small")
latex_lines.append(r"\renewcommand{\arraystretch}{1.10}")
latex_lines.append(r"\setlength{\tabcolsep}{5pt}")
latex_lines.append("")

# Panel A
latex_lines.append(
    r"\multicolumn{3}{l}{\textbf{Panel A. "
    r"Assessment-design leakage during representation refinement}}\\[2pt]"
)
latex_lines.append(
    r"\begin{tabular}{@{}lrr@{}}"
)
latex_lines.append(r"\toprule")
latex_lines.append(
    r"\textbf{Representation stage} & "
    r"\textbf{Balanced accuracy} & "
    r"\textbf{Reduction vs. raw (\%)} \\"
)
latex_lines.append(r"\midrule")

for _, r in panel_a.iterrows():
    latex_lines.append(
        f"{r['Representation stage']} & "
        f"{r['Design-leakage balanced accuracy']:.4f} & "
        f"{r['Reduction vs. raw (%)']:.1f} \\\\"
    )

latex_lines.append(r"\bottomrule")
latex_lines.append(r"\end{tabular}")
latex_lines.append(r"\vspace{0.8em}")
latex_lines.append("")

# Panel B
latex_lines.append(
    r"\multicolumn{7}{l}{\textbf{Panel B. "
    r"Hidden-target creative-signal retention before and after "
    r"design calibration}}\\[2pt]"
)
latex_lines.append(
    r"\begin{tabular}{@{}llrrrrr@{}}"
)
latex_lines.append(r"\toprule")
latex_lines.append(
    r"\textbf{Direction} & "
    r"\textbf{Representation} & "
    r"\textbf{Train $N$} & "
    r"\textbf{Validation $N$} & "
    r"\textbf{$R^2$} & "
    r"\textbf{MAE} & "
    r"\textbf{Spearman $\rho$} \\"
)
latex_lines.append(r"\midrule")

for _, r in panel_b.iterrows():
    latex_lines.append(
        f"{r['Direction']} & "
        f"{r['Representation']} & "
        f"{int(r['Train N']):,} & "
        f"{int(r['Validation N']):,} & "
        f"{r['R2']:.4f} & "
        f"{r['MAE']:.4f} & "
        f"{r['Spearman rho']:.4f} \\\\"
    )

latex_lines.append(r"\bottomrule")
latex_lines.append(r"\end{tabular}")
latex_lines.append("")
latex_lines.append(
    r"\begin{flushleft}"
    r"\footnotesize "
    r"\textit{Note.} These analyses belong to the Fold-0 "
    r"architecture-development stage and were conducted before "
    r"confirmatory access to the held-out test systems. "
    r"The design-leakage balanced-accuracy probe in Panel A is "
    r"reported as recorded in the locked development outputs. "
    r"Panel B uses the fixed disjoint-item A$\rightarrow$B and "
    r"B$\rightarrow$A validation protocol. Design calibration "
    r"reduced the leakage probe from 0.3183 to 0.1724 while the "
    r"mean hidden-target Spearman correlation remained essentially "
    r"unchanged."
    r"\end{flushleft}"
)
latex_lines.append(r"\end{table*}")

latex_text = "\n".join(latex_lines)

tex_path = (
    SUPP_TABLE_DIR /
    "Table_S3_design_calibration_and_signal_retention.tex"
)

tex_path.write_text(latex_text, encoding="utf-8")

print("\nSaved:")
print(panel_a_path)
print(panel_b_path)
print(tex_path)

print("\n" + "=" * 120)
print("LATEX PREVIEW")
print("=" * 120)
print(latex_text)

========================================================================================================================
SUPPLEMENTARY TABLE S3 - PANEL A
========================================================================================================================

                             Representation stage  Design-leakage balanced accuracy  Reduction vs. raw (%)
0                    Raw mask-free representation                            0.3183                 0.0000
1                Item-residualised representation                            0.2273                28.6038
2  Country-equal design-calibrated representation                            0.1724                45.8340

========================================================================================================================
SUPPLEMENTARY TABLE S3 - PANEL B
========================================================================================================================

         Direction     Representation  Train N  Validation N      R2     MAE  Spearman rho
0  A$\rightarrow$B  Item-residualised    94046         19312  0.3945  0.1712        0.6468
1  A$\rightarrow$B  Design-calibrated    94046         19312  0.3939  0.1714        0.6469
2  B$\rightarrow$A  Item-residualised    95332         19370  0.4217  0.1604        0.6623
3  B$\rightarrow$A  Design-calibrated    95332         19370  0.4222  0.1604        0.6630

========================================================================================================================
SUMMARY
========================================================================================================================
Raw design-leakage BA                : 0.318307
Final calibrated design-leakage BA   : 0.172414
Relative reduction                   : 45.83%
Mean residualised hidden-target rho  : 0.654533
Mean calibrated hidden-target rho    : 0.654943
Change in mean hidden-target rho     : +0.000411

Saved:
PROJECT_ROOT\results\supplementary_material\tables\Table_S3A_design_calibration_progression.csv
PROJECT_ROOT\results\supplementary_material\tables\Table_S3B_design_calibration_signal_retention.csv
PROJECT_ROOT\results\supplementary_material\tables\Table_S3_design_calibration_and_signal_retention.tex

========================================================================================================================
LATEX PREVIEW
========================================================================================================================
\begin{table*}[t]
\caption{Development-stage assessment-design calibration and hidden-target creative-signal retention. Panel A reports the progressive reduction in design-leakage probe performance during Fold-0 architecture development. Panel B verifies that the final design-calibration step did not materially reduce hidden-target creative-signal transfer on the validation systems.}
\label{tab:supp_design_calibration}
\centering
\small
\renewcommand{\arraystretch}{1.10}
\setlength{\tabcolsep}{5pt}

\multicolumn{3}{l}{\textbf{Panel A. Assessment-design leakage during representation refinement}}\\[2pt]
\begin{tabular}{@{}lrr@{}}
\toprule
\textbf{Representation stage} & \textbf{Balanced accuracy} & \textbf{Reduction vs. raw (\%)} \\
\midrule
Raw mask-free representation & 0.3183 & 0.0 \\
Item-residualised representation & 0.2273 & 28.6 \\
Country-equal design-calibrated representation & 0.1724 & 45.8 \\
\bottomrule
\end{tabular}
\vspace{0.8em}

\multicolumn{7}{l}{\textbf{Panel B. Hidden-target creative-signal retention before and after design calibration}}\\[2pt]
\begin{tabular}{@{}llrrrrr@{}}
\toprule
\textbf{Direction} & \textbf{Representation} & \textbf{Train $N$} & \textbf{Validation $N$} & \textbf{$R^2$} & \textbf{MAE} & \textbf{Spearman $\rho$} \\
\midrule
A$\rightarrow$B & Item-residualised & 94,046 & 19,312 & 0.3945 & 0.1712 & 0.6468 \\
A$\rightarrow$B & Design-calibrated & 94,046 & 19,312 & 0.3939 & 0.1714 & 0.6469 \\
B$\rightarrow$A & Item-residualised & 95,332 & 19,370 & 0.4217 & 0.1604 & 0.6623 \\
B$\rightarrow$A & Design-calibrated & 95,332 & 19,370 & 0.4222 & 0.1604 & 0.6630 \\
\bottomrule
\end{tabular}

\begin{flushleft}\footnotesize \textit{Note.} These analyses belong to the Fold-0 architecture-development stage and were conducted before confirmatory access to the held-out test systems. The design-leakage balanced-accuracy probe in Panel A is reported as recorded in the locked development outputs. Panel B uses the fixed disjoint-item A$\rightarrow$B and B$\rightarrow$A validation protocol. Design calibration reduced the leakage probe from 0.3183 to 0.1724 while the mean hidden-target Spearman correlation remained essentially unchanged.\end{flushleft}
\end{table*}

In [ ]:
# Fix Supplementary Table S3 LaTeX structure

latex_lines = []

latex_lines.append(r"\begin{table*}[t]")
latex_lines.append(
    r"\caption{Development-stage assessment-design calibration and "
    r"hidden-target creative-signal retention. Panel A reports the "
    r"progressive reduction in design-leakage probe performance during "
    r"Fold-0 architecture development. Panel B verifies that the final "
    r"design-calibration step did not materially reduce hidden-target "
    r"creative-signal transfer on the validation systems.}"
)
latex_lines.append(r"\label{tab:supp_design_calibration}")
latex_lines.append(r"\centering")
latex_lines.append(r"\small")
latex_lines.append(r"\renewcommand{\arraystretch}{1.10}")
latex_lines.append("")

# Panel A

latex_lines.append(
    r"\textbf{Panel A. Assessment-design leakage during representation refinement}"
)
latex_lines.append(r"\par\smallskip")
latex_lines.append(
    r"\begin{tabular}{@{}lrr@{}}"
)
latex_lines.append(r"\toprule")
latex_lines.append(
    r"\textbf{Representation stage} & "
    r"\textbf{Balanced accuracy} & "
    r"\textbf{Reduction vs. raw (\%)} \\"
)
latex_lines.append(r"\midrule")

for _, r in panel_a.iterrows():
    latex_lines.append(
        f"{r['Representation stage']} & "
        f"{r['Design-leakage balanced accuracy']:.4f} & "
        f"{r['Reduction vs. raw (%)']:.1f} \\\\"
    )

latex_lines.append(r"\bottomrule")
latex_lines.append(r"\end{tabular}")

latex_lines.append(r"\vspace{1em}")

# Panel B

latex_lines.append(
    r"\textbf{Panel B. Hidden-target creative-signal retention before and after design calibration}"
)
latex_lines.append(r"\par\smallskip")
latex_lines.append(
    r"\begin{tabular}{@{}llrrrrr@{}}"
)
latex_lines.append(r"\toprule")
latex_lines.append(
    r"\textbf{Direction} & "
    r"\textbf{Representation} & "
    r"\textbf{Train $N$} & "
    r"\textbf{Validation $N$} & "
    r"\textbf{$R^2$} & "
    r"\textbf{MAE} & "
    r"\textbf{Spearman $\rho$} \\"
)
latex_lines.append(r"\midrule")

for _, r in panel_b.iterrows():
    latex_lines.append(
        f"{r['Direction']} & "
        f"{r['Representation']} & "
        f"{int(r['Train N']):,} & "
        f"{int(r['Validation N']):,} & "
        f"{r['R2']:.4f} & "
        f"{r['MAE']:.4f} & "
        f"{r['Spearman rho']:.4f} \\\\"
    )

latex_lines.append(r"\bottomrule")
latex_lines.append(r"\end{tabular}")

latex_lines.append("")
latex_lines.append(
    r"\begin{flushleft}"
    r"\footnotesize "
    r"\textit{Note.} These analyses belong to the Fold-0 "
    r"architecture-development stage and were conducted before "
    r"confirmatory access to the held-out test systems. "
    r"Panel B uses the fixed disjoint-item A$\rightarrow$B and "
    r"B$\rightarrow$A validation protocol. Design calibration reduced "
    r"the recorded design-leakage balanced accuracy from 0.3183 to "
    r"0.1724 (45.8\% relative reduction), while mean hidden-target "
    r"Spearman correlation changed only from 0.6545 to 0.6549."
    r"\end{flushleft}"
)

latex_lines.append(r"\end{table*}")

latex_text = "\n".join(latex_lines)

tex_path = (
    SUPP_TABLE_DIR /
    "Table_S3_design_calibration_and_signal_retention.tex"
)

tex_path.write_text(latex_text, encoding="utf-8")

print("Corrected LaTeX saved:")
print(tex_path)

print("\n" + "=" * 120)
print("CORRECTED LATEX PREVIEW")
print("=" * 120)
print(latex_text)

Corrected LaTeX saved:
PROJECT_ROOT\results\supplementary_material\tables\Table_S3_design_calibration_and_signal_retention.tex

========================================================================================================================
CORRECTED LATEX PREVIEW
========================================================================================================================
\begin{table*}[t]
\caption{Development-stage assessment-design calibration and hidden-target creative-signal retention. Panel A reports the progressive reduction in design-leakage probe performance during Fold-0 architecture development. Panel B verifies that the final design-calibration step did not materially reduce hidden-target creative-signal transfer on the validation systems.}
\label{tab:supp_design_calibration}
\centering
\small
\renewcommand{\arraystretch}{1.10}

\textbf{Panel A. Assessment-design leakage during representation refinement}
\par\smallskip
\begin{tabular}{@{}lrr@{}}
\toprule
\textbf{Representation stage} & \textbf{Balanced accuracy} & \textbf{Reduction vs. raw (\%)} \\
\midrule
Raw mask-free representation & 0.3183 & 0.0 \\
Item-residualised representation & 0.2273 & 28.6 \\
Country-equal design-calibrated representation & 0.1724 & 45.8 \\
\bottomrule
\end{tabular}
\vspace{1em}
\textbf{Panel B. Hidden-target creative-signal retention before and after design calibration}
\par\smallskip
\begin{tabular}{@{}llrrrrr@{}}
\toprule
\textbf{Direction} & \textbf{Representation} & \textbf{Train $N$} & \textbf{Validation $N$} & \textbf{$R^2$} & \textbf{MAE} & \textbf{Spearman $\rho$} \\
\midrule
A$\rightarrow$B & Item-residualised & 94,046 & 19,312 & 0.3945 & 0.1712 & 0.6468 \\
A$\rightarrow$B & Design-calibrated & 94,046 & 19,312 & 0.3939 & 0.1714 & 0.6469 \\
B$\rightarrow$A & Item-residualised & 95,332 & 19,370 & 0.4217 & 0.1604 & 0.6623 \\
B$\rightarrow$A & Design-calibrated & 95,332 & 19,370 & 0.4222 & 0.1604 & 0.6630 \\
\bottomrule
\end{tabular}

\begin{flushleft}\footnotesize \textit{Note.} These analyses belong to the Fold-0 architecture-development stage and were conducted before confirmatory access to the held-out test systems. Panel B uses the fixed disjoint-item A$\rightarrow$B and B$\rightarrow$A validation protocol. Design calibration reduced the recorded design-leakage balanced accuracy from 0.3183 to 0.1724 (45.8\% relative reduction), while mean hidden-target Spearman correlation changed only from 0.6545 to 0.6549.\end{flushleft}
\end{table*}

In [ ]:
# Build Supplementary Table S4:
# Final cross-system nuisance-probe results

import pandas as pd
import numpy as np

final_nuisance = pd.read_csv(
    RESULTS_DIR / "crest_final_crosssystem_nuisance_summary.csv"
)

# Publication labels

representation_map = {
    "design_mask": "Design-mask positive control",
    "z_general": r"General creative representation ($\mathbf{z}^{g}$)",
    "z_context": r"Context representation ($\mathbf{z}^{c}$)",
}

target_map = {
    "booklet": "Booklet",
    "design_signature": "Design signature",
}

table_s4 = final_nuisance.copy()

table_s4["Representation"] = (
    table_s4["representation"]
    .map(representation_map)
    .fillna(table_s4["representation"])
)

table_s4["Target"] = (
    table_s4["target"]
    .map(target_map)
    .fillna(table_s4["target"])
)

table_s4 = table_s4[
    [
        "Representation",
        "Target",
        "chance",
        "balanced_accuracy_mean",
        "balanced_accuracy_sd",
        "macro_f1_mean",
        "macro_f1_sd",
        "absolute_excess_over_chance",
    ]
].rename(
    columns={
        "chance": "Chance BA",
        "balanced_accuracy_mean": "Balanced accuracy",
        "balanced_accuracy_sd": "BA SD",
        "macro_f1_mean": "Macro F1",
        "macro_f1_sd": "F1 SD",
        "absolute_excess_over_chance": "Excess over chance",
    }
)

# Compute suppression relative to design-mask positive control

suppression = {}

for target in ["booklet", "design_signature"]:

    control = float(
        final_nuisance.loc[
            (final_nuisance["representation"] == "design_mask")
            & (final_nuisance["target"] == target),
            "balanced_accuracy_mean"
        ].iloc[0]
    )

    general = float(
        final_nuisance.loc[
            (final_nuisance["representation"] == "z_general")
            & (final_nuisance["target"] == target),
            "balanced_accuracy_mean"
        ].iloc[0]
    )

    chance = float(
        final_nuisance.loc[
            (final_nuisance["representation"] == "z_general")
            & (final_nuisance["target"] == target),
            "chance"
        ].iloc[0]
    )

    # Suppression of excess nuisance information above chance
    suppression_pct = (
        1 - ((general - chance) / (control - chance))
    ) * 100

    suppression[target] = suppression_pct

print("=" * 120)
print("SUPPLEMENTARY TABLE S4")
print("=" * 120)

display(
    table_s4.round({
        "Chance BA": 4,
        "Balanced accuracy": 4,
        "BA SD": 4,
        "Macro F1": 4,
        "F1 SD": 4,
        "Excess over chance": 4,
    })
)

print("\n" + "=" * 120)
print("NUISANCE SUPPRESSION")
print("=" * 120)

print(
    f"Booklet nuisance suppression       : "
    f"{suppression['booklet']:.2f}%"
)

print(
    f"Design-signature suppression       : "
    f"{suppression['design_signature']:.2f}%"
)

# Save CSV

csv_path = (
    SUPP_TABLE_DIR /
    "Table_S4_final_crosssystem_nuisance_probes.csv"
)

table_s4.to_csv(csv_path, index=False)

# Generate LaTeX

latex_lines = []

latex_lines.append(r"\begin{table*}[t]")
latex_lines.append(
    r"\caption{Final cross-system nuisance-probe performance for "
    r"assessment-design information in the frozen CReST representations.}"
)
latex_lines.append(r"\label{tab:supp_nuisance_probes}")
latex_lines.append(r"\centering")
latex_lines.append(r"\small")
latex_lines.append(r"\renewcommand{\arraystretch}{1.10}")
latex_lines.append(r"\setlength{\tabcolsep}{5pt}")
latex_lines.append("")
latex_lines.append(
    r"\begin{tabular}{@{}llrrrrrr@{}}"
)
latex_lines.append(r"\toprule")
latex_lines.append(
    r"\textbf{Representation} & "
    r"\textbf{Target} & "
    r"\textbf{Chance BA} & "
    r"\textbf{BA} & "
    r"\textbf{BA SD} & "
    r"\textbf{Macro F1} & "
    r"\textbf{F1 SD} & "
    r"\textbf{Excess over chance} \\"
)
latex_lines.append(r"\midrule")

for _, r in table_s4.iterrows():
    latex_lines.append(
        f"{r['Representation']} & "
        f"{r['Target']} & "
        f"{r['Chance BA']:.4f} & "
        f"{r['Balanced accuracy']:.4f} & "
        f"{r['BA SD']:.4f} & "
        f"{r['Macro F1']:.4f} & "
        f"{r['F1 SD']:.4f} & "
        f"{r['Excess over chance']:.4f} \\\\"
    )

latex_lines.append(r"\bottomrule")
latex_lines.append(r"\end{tabular}")
latex_lines.append("")
latex_lines.append(
    r"\begin{flushleft}"
    r"\footnotesize "
    r"\textit{Note.} Values are averaged across the final cross-system "
    r"nuisance probes. The design mask provides a positive control for "
    r"the information available from the matrix-sampled assessment "
    r"structure. Balanced accuracy for the general creative representation "
    r"was 0.0704 for booklet prediction and 0.2231 for design-signature "
    r"prediction, compared with positive-control values of 0.3333 and "
    r"1.0000, respectively. Relative to the positive control and after "
    r"accounting for chance performance, this corresponds to "
    f"{suppression['booklet']:.1f}\\% suppression of booklet information "
    r"and "
    f"{suppression['design_signature']:.1f}\\% suppression of "
    r"design-signature information. The contextual representation was "
    r"approximately at chance for both targets."
    r"\end{flushleft}"
)
latex_lines.append(r"\end{table*}")

latex_text = "\n".join(latex_lines)

tex_path = (
    SUPP_TABLE_DIR /
    "Table_S4_final_crosssystem_nuisance_probes.tex"
)

tex_path.write_text(latex_text, encoding="utf-8")

print("\nSaved CSV:")
print(csv_path)

print("\nSaved LaTeX:")
print(tex_path)

print("\n" + "=" * 120)
print("LATEX PREVIEW")
print("=" * 120)
print(latex_text)

========================================================================================================================
SUPPLEMENTARY TABLE S4
========================================================================================================================

                                      Representation            Target  Chance BA  Balanced accuracy   BA SD  Macro F1   F1 SD  Excess over chance
0                       Design-mask positive control           Booklet     0.0333             0.3333  0.0000    0.1911  0.0507              0.3000
1                       Design-mask positive control  Design signature     0.1000             1.0000  0.0000    1.0000  0.0000              0.9000
2          Context representation ($\mathbf{z}^{c}$)           Booklet     0.0333             0.0318  0.0022    0.0075  0.0009             -0.0016
3          Context representation ($\mathbf{z}^{c}$)  Design signature     0.1000             0.0985  0.0019    0.0965  0.0019             -0.0015
4  General creative representation ($\mathbf{z}^{...           Booklet     0.0333             0.0704  0.0061    0.0306  0.0054              0.0371
5  General creative representation ($\mathbf{z}^{...  Design signature     0.1000             0.2231  0.0146    0.2086  0.0147              0.1231

========================================================================================================================
NUISANCE SUPPRESSION
========================================================================================================================
Booklet nuisance suppression       : 87.64%
Design-signature suppression       : 86.32%

Saved CSV:
PROJECT_ROOT\results\supplementary_material\tables\Table_S4_final_crosssystem_nuisance_probes.csv

Saved LaTeX:
PROJECT_ROOT\results\supplementary_material\tables\Table_S4_final_crosssystem_nuisance_probes.tex

========================================================================================================================
LATEX PREVIEW
========================================================================================================================
\begin{table*}[t]
\caption{Final cross-system nuisance-probe performance for assessment-design information in the frozen CReST representations.}
\label{tab:supp_nuisance_probes}
\centering
\small
\renewcommand{\arraystretch}{1.10}
\setlength{\tabcolsep}{5pt}

\begin{tabular}{@{}llrrrrrr@{}}
\toprule
\textbf{Representation} & \textbf{Target} & \textbf{Chance BA} & \textbf{BA} & \textbf{BA SD} & \textbf{Macro F1} & \textbf{F1 SD} & \textbf{Excess over chance} \\
\midrule
Design-mask positive control & Booklet & 0.0333 & 0.3333 & 0.0000 & 0.1911 & 0.0507 & 0.3000 \\
Design-mask positive control & Design signature & 0.1000 & 1.0000 & 0.0000 & 1.0000 & 0.0000 & 0.9000 \\
Context representation ($\mathbf{z}^{c}$) & Booklet & 0.0333 & 0.0318 & 0.0022 & 0.0075 & 0.0009 & -0.0016 \\
Context representation ($\mathbf{z}^{c}$) & Design signature & 0.1000 & 0.0985 & 0.0019 & 0.0965 & 0.0019 & -0.0015 \\
General creative representation ($\mathbf{z}^{g}$) & Booklet & 0.0333 & 0.0704 & 0.0061 & 0.0306 & 0.0054 & 0.0371 \\
General creative representation ($\mathbf{z}^{g}$) & Design signature & 0.1000 & 0.2231 & 0.0146 & 0.2086 & 0.0147 & 0.1231 \\
\bottomrule
\end{tabular}

\begin{flushleft}\footnotesize \textit{Note.} Values are averaged across the final cross-system nuisance probes. The design mask provides a positive control for the information available from the matrix-sampled assessment structure. Balanced accuracy for the general creative representation was 0.0704 for booklet prediction and 0.2231 for design-signature prediction, compared with positive-control values of 0.3333 and 1.0000, respectively. Relative to the positive control and after accounting for chance performance, this corresponds to 87.6\% suppression of booklet information and 86.3\% suppression of design-signature information. The contextual representation was approximately at chance for both targets.\end{flushleft}
\end{table*}

In [ ]:
# Inspect domain- and process-specific summary files

domain_summary = pd.read_csv(
    RESULTS_DIR / "crest_domain_increment_summary.csv"
)

process_summary = pd.read_csv(
    RESULTS_DIR / "crest_process_increment_summary.csv"
)

print("=" * 110)
print("A. DOMAIN-SPECIFIC INCREMENT SUMMARY")
print("=" * 110)

print("Shape:", domain_summary.shape)
print("Columns:", domain_summary.columns.tolist())
display(domain_summary)


print("\n" + "=" * 110)
print("B. PROCESS-ANCHORED INCREMENT SUMMARY")
print("=" * 110)

print("Shape:", process_summary.shape)
print("Columns:", process_summary.columns.tolist())
display(process_summary)

In [ ]:
# Inspect system-level domain/process increment results
# before constructing Supplementary Table S5

domain_7fold = pd.read_csv(
    RESULTS_DIR / "crest_domain_increment_7fold.csv"
)

process_7fold = pd.read_csv(
    RESULTS_DIR / "crest_process_increment_7fold.csv"
)

print("=" * 110)
print("A. DOMAIN-SPECIFIC SYSTEM-LEVEL RESULTS")
print("=" * 110)

print("Shape:", domain_7fold.shape)
print("Columns:", domain_7fold.columns.tolist())
display(domain_7fold.head(15))


print("\n" + "=" * 110)
print("B. PROCESS-ANCHORED SYSTEM-LEVEL RESULTS")
print("=" * 110)

print("Shape:", process_7fold.shape)
print("Columns:", process_7fold.columns.tolist())
display(process_7fold.head(15))

In [ ]:
# Locate system-level domain/process increment outputs

from pathlib import Path
import pandas as pd

candidates = []

for path in RESULTS_DIR.rglob("*.csv"):
    try:
        df = pd.read_csv(path, nrows=5)

        cols = {c.lower() for c in df.columns}

        # Likely identifiers for system-level results
        has_system_id = any(
            c in cols
            for c in [
                "cnt",
                "country",
                "system",
                "education_system",
                "country_code",
            ]
        )

        has_increment = any(
            "delta_rho" in c.lower()
            or "combined_rho" in c.lower()
            for c in df.columns
        )

        has_domain_or_process = any(
            c in cols
            for c in ["domain", "process"]
        )

        if has_system_id and has_increment and has_domain_or_process:
            candidates.append({
                "file": str(path.relative_to(BASE_DIR)),
                "columns": ", ".join(df.columns),
            })

    except Exception:
        pass

candidate_df = pd.DataFrame(candidates)

print("=" * 120)
print("CANDIDATE SYSTEM-LEVEL DOMAIN / PROCESS FILES")
print("=" * 120)

if len(candidate_df):
    display(candidate_df)
else:
    print("No obvious system-level candidate files found.")

In [ ]:
# Inspect true system-level domain/process increment outputs

domain_63 = pd.read_csv(
    RESULTS_DIR / "crest_domain_increment_63system.csv"
)

process_63 = pd.read_csv(
    RESULTS_DIR / "crest_process_increment_63system.csv"
)

print("=" * 120)
print("A. DOMAIN-SPECIFIC 63-SYSTEM RESULTS")
print("=" * 120)

print("Shape:", domain_63.shape)
print("Columns:", domain_63.columns.tolist())
display(domain_63.head(20))


print("\n" + "=" * 120)
print("B. PROCESS-ANCHORED 63-SYSTEM RESULTS")
print("=" * 120)

print("Shape:", process_63.shape)
print("Columns:", process_63.columns.tolist())
display(process_63.head(20))


print("\n" + "=" * 120)
print("BASIC STRUCTURE CHECKS")
print("=" * 120)

print(
    "Domain systems:",
    domain_63["country"].nunique()
)

print(
    "Domain directions:",
    sorted(domain_63["direction"].unique())
)

print(
    "Domain categories:",
    sorted(domain_63["domain"].unique())
)

print(
    "Process systems:",
    process_63["country"].nunique()
)

print(
    "Process directions:",
    sorted(process_63["direction"].unique())
)

print(
    "Process categories:",
    sorted(process_63["process"].unique())
)

In [ ]:
# Build Supplementary Table S5:
# Domain- and process-specific incremental information
# with 63-system bootstrap confidence intervals

import numpy as np
import pandas as pd

BOOTSTRAP_REPS = 50_000
BOOTSTRAP_SEED = 20270017

# Collapse A->B and B->A within each education system

domain_system = (
    domain_63
    .groupby(["domain", "country"], as_index=False)
    .agg(
        delta_rho=("delta_rho", "mean"),
        general_rho=("general_rho", "mean"),
        combined_rho=("combined_rho", "mean"),
    )
)

process_system = (
    process_63
    .groupby(["process", "country"], as_index=False)
    .agg(
        delta_rho=("delta_rho", "mean"),
        general_rho=("general_rho", "mean"),
        combined_rho=("combined_rho", "mean"),
    )
)

assert (domain_system.groupby("domain")["country"].nunique() == 63).all()
assert (process_system.groupby("process")["country"].nunique() == 63).all()


# System-level bootstrap helper

def system_bootstrap_summary(
    df,
    category_col,
    value_col="delta_rho",
    n_boot=50_000,
    seed=20270017,
):
    rng = np.random.default_rng(seed)

    rows = []

    for category, g in df.groupby(category_col, sort=False):

        values = g[value_col].to_numpy(dtype=float)
        n = len(values)

        estimate = values.mean()

        boot_idx = rng.integers(
            0,
            n,
            size=(n_boot, n)
        )

        boot_means = values[boot_idx].mean(axis=1)

        ci_low, ci_high = np.quantile(
            boot_means,
            [0.025, 0.975]
        )

        positive = int((values > 0).sum())

        rows.append({
            category_col: category,
            "systems": n,
            "system_equal_delta_rho": estimate,
            "ci_low": ci_low,
            "ci_high": ci_high,
            "median_delta_rho": np.median(values),
            "systems_positive": positive,
            "pct_systems_positive": positive / n * 100,
        })

    return pd.DataFrame(rows)


domain_boot = system_bootstrap_summary(
    domain_system,
    category_col="domain",
    n_boot=BOOTSTRAP_REPS,
    seed=BOOTSTRAP_SEED
)

process_boot = system_bootstrap_summary(
    process_system,
    category_col="process",
    n_boot=BOOTSTRAP_REPS,
    seed=BOOTSTRAP_SEED + 1
)


# Audit mean estimates against locked summary outputs

domain_locked = domain_summary[
    [
        "domain",
        "country_equal_delta_rho_mean",
    ]
].copy()

process_locked = process_summary[
    [
        "process",
        "country_equal_delta_rho_mean",
    ]
].copy()

domain_audit = domain_boot.merge(
    domain_locked,
    on="domain",
    how="left",
    validate="one_to_one"
)

process_audit = process_boot.merge(
    process_locked,
    on="process",
    how="left",
    validate="one_to_one"
)

domain_audit["mean_difference"] = (
    domain_audit["system_equal_delta_rho"]
    - domain_audit["country_equal_delta_rho_mean"]
)

process_audit["mean_difference"] = (
    process_audit["system_equal_delta_rho"]
    - process_audit["country_equal_delta_rho_mean"]
)


# Display audit

print("=" * 120)
print("DOMAIN AUDIT")
print("=" * 120)

display(
    domain_audit[
        [
            "domain",
            "system_equal_delta_rho",
            "country_equal_delta_rho_mean",
            "mean_difference",
            "ci_low",
            "ci_high",
            "systems_positive",
            "pct_systems_positive",
            "median_delta_rho",
        ]
    ].round(6)
)

print("\n" + "=" * 120)
print("PROCESS AUDIT")
print("=" * 120)

display(
    process_audit[
        [
            "process",
            "system_equal_delta_rho",
            "country_equal_delta_rho_mean",
            "mean_difference",
            "ci_low",
            "ci_high",
            "systems_positive",
            "pct_systems_positive",
            "median_delta_rho",
        ]
    ].round(6)
)

domain_match = np.allclose(
    domain_audit["system_equal_delta_rho"],
    domain_audit["country_equal_delta_rho_mean"],
    atol=1e-12
)

process_match = np.allclose(
    process_audit["system_equal_delta_rho"],
    process_audit["country_equal_delta_rho_mean"],
    atol=1e-12
)

print("\nMean estimates reproduce locked summaries:")
print("Domains :", domain_match)
print("Processes:", process_match)


# Publication ordering

domain_order = [
    "Social",
    "Scientific",
    "Written",
    "Visual",
]

process_order = [
    "GDI",
    "EII",
    "GCI",
]

domain_boot["order"] = domain_boot["domain"].map(
    {v: i for i, v in enumerate(domain_order)}
)

process_boot["order"] = process_boot["process"].map(
    {v: i for i, v in enumerate(process_order)}
)

domain_boot = (
    domain_boot
    .sort_values("order")
    .drop(columns="order")
    .reset_index(drop=True)
)

process_boot = (
    process_boot
    .sort_values("order")
    .drop(columns="order")
    .reset_index(drop=True)
)


# Save CSV outputs

domain_csv = (
    SUPP_TABLE_DIR /
    "Table_S5A_domain_specific_increment_bootstrap.csv"
)

process_csv = (
    SUPP_TABLE_DIR /
    "Table_S5B_process_specific_increment_bootstrap.csv"
)

domain_boot.to_csv(domain_csv, index=False)
process_boot.to_csv(process_csv, index=False)


# Generate LaTeX Table S5

latex_lines = []

latex_lines.append(r"\begin{table*}[t]")
latex_lines.append(
    r"\caption{Incremental hidden-target information contributed by "
    r"domain-specific and process-anchored CReST representations beyond "
    r"the general creative representation. Estimates give equal weight "
    r"to each of the 63 education systems.}"
)
latex_lines.append(r"\label{tab:supp_domain_process_increment}")
latex_lines.append(r"\centering")
latex_lines.append(r"\small")
latex_lines.append(r"\renewcommand{\arraystretch}{1.10}")
latex_lines.append("")

# Panel A
latex_lines.append(
    r"\textbf{Panel A. Domain-specific representations}"
)
latex_lines.append(r"\par\smallskip")
latex_lines.append(
    r"\begin{tabular}{@{}lrrrrr@{}}"
)
latex_lines.append(r"\toprule")
latex_lines.append(
    r"\textbf{Domain} & "
    r"\textbf{$\Delta\rho$} & "
    r"\textbf{95\% CI} & "
    r"\textbf{Positive systems} & "
    r"\textbf{Positive (\%)} & "
    r"\textbf{Median $\Delta\rho$} \\"
)
latex_lines.append(r"\midrule")

for _, r in domain_boot.iterrows():
    latex_lines.append(
        f"{r['domain']} & "
        f"{r['system_equal_delta_rho']:.4f} & "
        f"[{r['ci_low']:.4f}, {r['ci_high']:.4f}] & "
        f"{int(r['systems_positive'])}/63 & "
        f"{r['pct_systems_positive']:.1f} & "
        f"{r['median_delta_rho']:.4f} \\\\"
    )

latex_lines.append(r"\bottomrule")
latex_lines.append(r"\end{tabular}")

latex_lines.append(r"\vspace{1em}")

# Panel B
latex_lines.append(
    r"\textbf{Panel B. Process-anchored representations}"
)
latex_lines.append(r"\par\smallskip")
latex_lines.append(
    r"\begin{tabular}{@{}lrrrrr@{}}"
)
latex_lines.append(r"\toprule")
latex_lines.append(
    r"\textbf{Process} & "
    r"\textbf{$\Delta\rho$} & "
    r"\textbf{95\% CI} & "
    r"\textbf{Positive systems} & "
    r"\textbf{Positive (\%)} & "
    r"\textbf{Median $\Delta\rho$} \\"
)
latex_lines.append(r"\midrule")

for _, r in process_boot.iterrows():
    latex_lines.append(
        f"{r['process']} & "
        f"{r['system_equal_delta_rho']:.4f} & "
        f"[{r['ci_low']:.4f}, {r['ci_high']:.4f}] & "
        f"{int(r['systems_positive'])}/63 & "
        f"{r['pct_systems_positive']:.1f} & "
        f"{r['median_delta_rho']:.4f} \\\\"
    )

latex_lines.append(r"\bottomrule")
latex_lines.append(r"\end{tabular}")

latex_lines.append("")
latex_lines.append(
    r"\begin{flushleft}"
    r"\footnotesize "
    r"\textit{Note.} $\Delta\rho$ is the within-system difference in "
    r"Spearman correlation between the combined representation "
    r"(general plus domain-specific or process-anchored representation) "
    r"and the general creative representation alone when predicting "
    r"completely hidden target-item performance. The A$\rightarrow$B "
    r"and B$\rightarrow$A estimates were first averaged within each "
    r"education system. Reported means then assign equal weight to the "
    r"63 systems. Confidence intervals are percentile intervals from "
    f"{BOOTSTRAP_REPS:,} nonparametric system-level bootstrap "
    r"resamples. Process representations are described as "
    r"\emph{process-anchored} because the process tokens interact "
    r"through self-attention and should not be interpreted as pure "
    r"independent process factors."
    r"\end{flushleft}"
)

latex_lines.append(r"\end{table*}")

latex_text = "\n".join(latex_lines)

tex_path = (
    SUPP_TABLE_DIR /
    "Table_S5_domain_process_increment.tex"
)

tex_path.write_text(
    latex_text,
    encoding="utf-8"
)

print("\nSaved:")
print(domain_csv)
print(process_csv)
print(tex_path)

print("\n" + "=" * 120)
print("LATEX PREVIEW")
print("=" * 120)
print(latex_text)

========================================================================================================================
DOMAIN AUDIT
========================================================================================================================

,domain,system_equal_delta_rho,country_equal_delta_rho_mean,mean_difference,ci_low,ci_high,systems_positive,pct_systems_positive,median_delta_rho
0,Scientific,0.052218,0.052218,-0.0,0.043550,0.060669,60,95.238095,0.050113
1,Social,0.105840,0.105840,-0.0,0.096461,0.116185,63,100.000000,0.101881
2,Visual,-0.000592,-0.000592,-0.0,-0.010615,0.009309,29,46.031746,-0.002636
3,Written,0.046578,0.046578,0.0,0.038356,0.057659,63,100.000000,0.038627

========================================================================================================================
PROCESS AUDIT
========================================================================================================================

  process  system_equal_delta_rho  country_equal_delta_rho_mean  mean_difference    ci_low   ci_high  systems_positive  pct_systems_positive  median_delta_rho
0     EII                0.006176                      0.006176             -0.0  0.003221  0.008691                54             85.714286          0.007148
1     GCI                0.003071                      0.003071              0.0  0.001504  0.004713                44             69.841270          0.002852
2     GDI                0.013086                      0.013086             -0.0  0.010728  0.015401                60             95.238095          0.012265

Mean estimates reproduce locked summaries:
Domains : True
Processes: True

Saved:
PROJECT_ROOT\results\supplementary_material\tables\Table_S5A_domain_specific_increment_bootstrap.csv
PROJECT_ROOT\results\supplementary_material\tables\Table_S5B_process_specific_increment_bootstrap.csv
PROJECT_ROOT\results\supplementary_material\tables\Table_S5_domain_process_increment.tex

========================================================================================================================
LATEX PREVIEW
========================================================================================================================
\begin{table*}[t]
\caption{Incremental hidden-target information contributed by domain-specific and process-anchored CReST representations beyond the general creative representation. Estimates give equal weight to each of the 63 education systems.}
\label{tab:supp_domain_process_increment}
\centering
\small
\renewcommand{\arraystretch}{1.10}

\textbf{Panel A. Domain-specific representations}
\par\smallskip
\begin{tabular}{@{}lrrrrr@{}}
\toprule
\textbf{Domain} & \textbf{$\Delta\rho$} & \textbf{95\% CI} & \textbf{Positive systems} & \textbf{Positive (\%)} & \textbf{Median $\Delta\rho$} \\
\midrule
Social & 0.1058 & [0.0965, 0.1162] & 63/63 & 100.0 & 0.1019 \\
Scientific & 0.0522 & [0.0435, 0.0607] & 60/63 & 95.2 & 0.0501 \\
Written & 0.0466 & [0.0384, 0.0577] & 63/63 & 100.0 & 0.0386 \\
Visual & -0.0006 & [-0.0106, 0.0093] & 29/63 & 46.0 & -0.0026 \\
\bottomrule
\end{tabular}
\vspace{1em}
\textbf{Panel B. Process-anchored representations}
\par\smallskip
\begin{tabular}{@{}lrrrrr@{}}
\toprule
\textbf{Process} & \textbf{$\Delta\rho$} & \textbf{95\% CI} & \textbf{Positive systems} & \textbf{Positive (\%)} & \textbf{Median $\Delta\rho$} \\
\midrule
GDI & 0.0131 & [0.0107, 0.0154] & 60/63 & 95.2 & 0.0123 \\
EII & 0.0062 & [0.0032, 0.0087] & 54/63 & 85.7 & 0.0071 \\
GCI & 0.0031 & [0.0015, 0.0047] & 44/63 & 69.8 & 0.0029 \\
\bottomrule
\end{tabular}

\begin{flushleft}\footnotesize \textit{Note.} $\Delta\rho$ is the within-system difference in Spearman correlation between the combined representation (general plus domain-specific or process-anchored representation) and the general creative representation alone when predicting completely hidden target-item performance. The A$\rightarrow$B and B$\rightarrow$A estimates were first averaged within each education system. Reported means then assign equal weight to the 63 systems. Confidence intervals are percentile intervals from 50,000 nonparametric system-level bootstrap resamples. Process representations are described as \emph{process-anchored} because the process tokens interact through self-attention and should not be interpreted as pure independent process factors.\end{flushleft}
\end{table*}

In [ ]:
# List actual survey-weighted population result files

survey_dir = RESULTS_DIR / "survey_weighted_population"

print("Directory:")
print(survey_dir)

print("\nFiles:")
for p in sorted(survey_dir.glob("*")):
    if p.is_file():
        print(p.name)

Directory:
PROJECT_ROOT\results\survey_weighted_population

Files:
crest_adjusted_associations_by_system_min30.csv
crest_adjusted_associations_by_system_min50.csv
crest_adjusted_associations_summary_min30.csv
crest_adjusted_associations_summary_min50.csv
crest_adjusted_min30_vs_min50.csv
crest_adjusted_model_support_audit.csv
crest_convergent_validity_pisa_ct_by_system.csv
crest_convergent_validity_pisa_ct_summary.csv
crest_convergent_validity_sensitivity.csv
crest_convergent_validity_system_influence.csv
crest_creative_pv_file_discovery.pkl
crest_population_adjusted_findings_LOCKED.csv
crest_population_analysis_base.pkl
crest_population_context_contrasts_by_system.csv
crest_population_context_contrasts_summary.csv
crest_population_context_system_bootstrap.csv
crest_population_standardized_effects_by_system.csv
crest_population_standardized_effects_summary.csv
crest_population_with_creative_pvs.pkl
crest_system_weighted_transfer_score.csv
crest_transfer_score_oof.pkl
crest_transfer_score_system_coverage.csv
desktop.ini

In [ ]:
# Inspect survey-weighted population/context result files

import pandas as pd

# Paths

survey_dir = RESULTS_DIR / "survey_weighted_population"

context_file = (
    survey_dir /
    "crest_population_context_contrasts_summary.csv"
)

adjusted_min30_file = (
    survey_dir /
    "crest_adjusted_associations_summary_min30.csv"
)

adjusted_min50_file = (
    survey_dir /
    "crest_adjusted_associations_summary_min50.csv"
)

# Load files

context_contrasts = pd.read_csv(
    context_file
)

adjusted_min30 = pd.read_csv(
    adjusted_min30_file
)

adjusted_min50 = pd.read_csv(
    adjusted_min50_file
)

# A. Unadjusted population context contrasts

print("=" * 120)
print("A. UNADJUSTED POPULATION CONTEXT CONTRASTS")
print("=" * 120)

print("File:", context_file.name)
print("Shape:", context_contrasts.shape)
print("Columns:", context_contrasts.columns.tolist())

display(context_contrasts)


# B. Adjusted associations - minimum support >= 30

print("\n" + "=" * 120)
print("B. ADJUSTED ASSOCIATIONS - MINIMUM SUPPORT 30")
print("=" * 120)

print("File:", adjusted_min30_file.name)
print("Shape:", adjusted_min30.shape)
print("Columns:", adjusted_min30.columns.tolist())

display(adjusted_min30)


# C. Adjusted associations - minimum support >= 50

print("\n" + "=" * 120)
print("C. ADJUSTED ASSOCIATIONS - MINIMUM SUPPORT 50")
print("=" * 120)

print("File:", adjusted_min50_file.name)
print("Shape:", adjusted_min50.shape)
print("Columns:", adjusted_min50.columns.tolist())

display(adjusted_min50)


# Basic integrity checks

print("\n" + "=" * 120)
print("BASIC INTEGRITY CHECKS")
print("=" * 120)

print(
    "Context contrasts file exists:",
    context_file.exists()
)

print(
    "Adjusted min30 file exists:",
    adjusted_min30_file.exists()
)

print(
    "Adjusted min50 file exists:",
    adjusted_min50_file.exists()
)

print(
    "Context contrasts rows:",
    len(context_contrasts)
)

print(
    "Adjusted min30 rows:",
    len(adjusted_min30)
)

print(
    "Adjusted min50 rows:",
    len(adjusted_min50)
)

In [ ]:
# Inspect bootstrap and sensitivity outputs
# for Supplementary Table S6

survey_dir = RESULTS_DIR / "survey_weighted_population"

context_bootstrap = pd.read_csv(
    survey_dir /
    "crest_population_context_system_bootstrap.csv"
)

adjusted_sensitivity = pd.read_csv(
    survey_dir /
    "crest_adjusted_min30_vs_min50.csv"
)

adjusted_locked = pd.read_csv(
    survey_dir /
    "crest_population_adjusted_findings_LOCKED.csv"
)

standardized_summary = pd.read_csv(
    survey_dir /
    "crest_population_standardized_effects_summary.csv"
)

print("=" * 120)
print("A. UNADJUSTED CONTEXT SYSTEM-BOOTSTRAP RESULTS")
print("=" * 120)

print("Shape:", context_bootstrap.shape)
print("Columns:", context_bootstrap.columns.tolist())
display(context_bootstrap)


print("\n" + "=" * 120)
print("B. ADJUSTED MIN30 vs MIN50 SENSITIVITY")
print("=" * 120)

print("Shape:", adjusted_sensitivity.shape)
print("Columns:", adjusted_sensitivity.columns.tolist())
display(adjusted_sensitivity)


print("\n" + "=" * 120)
print("C. LOCKED ADJUSTED FINDINGS")
print("=" * 120)

print("Shape:", adjusted_locked.shape)
print("Columns:", adjusted_locked.columns.tolist())
display(adjusted_locked)


print("\n" + "=" * 120)
print("D. STANDARDIZED EFFECTS SUMMARY")
print("=" * 120)

print("Shape:", standardized_summary.shape)
print("Columns:", standardized_summary.columns.tolist())
display(standardized_summary)

In [ ]:
# Build Supplementary Table S6:
# Survey-weighted contextual associations and sensitivity analysis

import pandas as pd
import numpy as np

survey_dir = RESULTS_DIR / "survey_weighted_population"

# Load locked source files

context_bootstrap = pd.read_csv(
    survey_dir /
    "crest_population_context_system_bootstrap.csv"
)

context_summary = pd.read_csv(
    survey_dir /
    "crest_population_context_contrasts_summary.csv"
)

standardized_summary = pd.read_csv(
    survey_dir /
    "crest_population_standardized_effects_summary.csv"
)

adjusted_locked = pd.read_csv(
    survey_dir /
    "crest_population_adjusted_findings_LOCKED.csv"
)

adjusted_min30 = pd.read_csv(
    survey_dir /
    "crest_adjusted_associations_summary_min30.csv"
)

# Panel A:
# Unadjusted survey-weighted contrasts
# Contrast direction = Group B - Group A

panel_a = (
    context_summary[
        [
            "contrast",
            "group_A",
            "group_B",
            "n_systems",
            "country_equal_difference",
        ]
    ]
    .merge(
        context_bootstrap[
            [
                "contrast",
                "system_boot_ci_low",
                "system_boot_ci_high",
                "positive_systems",
                "negative_systems",
            ]
        ],
        on="contrast",
        how="left",
        validate="one_to_one"
    )
    .merge(
        standardized_summary[
            [
                "contrast",
                "mean_standardized_difference",
                "system_boot_ci_low",
                "system_boot_ci_high",
            ]
        ].rename(
            columns={
                "system_boot_ci_low": "std_ci_low",
                "system_boot_ci_high": "std_ci_high",
            }
        ),
        on="contrast",
        how="left",
        validate="one_to_one"
    )
)

panel_a["Direction"] = (
    panel_a["group_B"].astype(str)
    + " $-$ "
    + panel_a["group_A"].astype(str)
)

panel_a["positive_pct"] = (
    panel_a["positive_systems"]
    / panel_a["n_systems"]
    * 100
)

panel_a = panel_a[
    [
        "contrast",
        "Direction",
        "n_systems",
        "country_equal_difference",
        "system_boot_ci_low",
        "system_boot_ci_high",
        "mean_standardized_difference",
        "std_ci_low",
        "std_ci_high",
        "positive_systems",
        "negative_systems",
        "positive_pct",
    ]
]

# Panel B:
# Adjusted associations, primary >=30 and sensitivity >=50

panel_b = adjusted_locked.copy()

# Add positive-system percentage from the primary min30 analysis
panel_b = panel_b.merge(
    adjusted_min30[
        [
            "coefficient",
            "pct_positive_systems",
        ]
    ],
    on="coefficient",
    how="left",
    validate="one_to_one"
)

# More publication-friendly labels
coefficient_labels = {
    "HOMEPOS": "Home-resource index (HOMEPOS)",
    "Male": "Male",
    "Repeated grade": "Repeated grade",
    "Immigrant background": "Immigrant background",
    "Language mismatch": "Home/test language mismatch",
    "Age": "Age",
}

panel_b["Predictor"] = (
    panel_b["coefficient"]
    .map(coefficient_labels)
    .fillna(panel_b["coefficient"])
)

panel_b = panel_b[
    [
        "Predictor",
        "primary_n_systems",
        "primary_estimate",
        "primary_ci_low",
        "primary_ci_high",
        "pct_positive_systems",
        "sensitivity_n_systems",
        "sensitivity_estimate",
        "sensitivity_ci_low",
        "sensitivity_ci_high",
        "same_direction_supported_both",
        "interpretation",
    ]
]

# Display

print("=" * 120)
print("SUPPLEMENTARY TABLE S6 - PANEL A")
print("=" * 120)

display(
    panel_a.round({
        "country_equal_difference": 6,
        "system_boot_ci_low": 6,
        "system_boot_ci_high": 6,
        "mean_standardized_difference": 6,
        "std_ci_low": 6,
        "std_ci_high": 6,
        "positive_pct": 1,
    })
)

print("\n" + "=" * 120)
print("SUPPLEMENTARY TABLE S6 - PANEL B")
print("=" * 120)

display(
    panel_b.round({
        "primary_estimate": 6,
        "primary_ci_low": 6,
        "primary_ci_high": 6,
        "pct_positive_systems": 1,
        "sensitivity_estimate": 6,
        "sensitivity_ci_low": 6,
        "sensitivity_ci_high": 6,
    })
)

# Integrity checks against locked headline results

checks = {
    "Home resources": 0.105813,
    "Grade repetition": -0.101497,
    "Immigrant background": -0.011724,
    "Gender": -0.038623,
    "Home/test language": -0.033724,
}

print("\n" + "=" * 120)
print("INTEGRITY CHECKS")
print("=" * 120)

for contrast, expected in checks.items():
    observed = float(
        panel_a.loc[
            panel_a["contrast"] == contrast,
            "country_equal_difference"
        ].iloc[0]
    )

    print(
        f"{contrast:<25} "
        f"observed={observed:+.6f} "
        f"expected={expected:+.6f} "
        f"match={np.isclose(observed, expected, atol=1e-6)}"
    )

print(
    "\nPrimary adjusted systems:",
    sorted(panel_b["primary_n_systems"].unique())
)

print(
    "Sensitivity adjusted systems:",
    sorted(panel_b["sensitivity_n_systems"].unique())
)

# Save CSV files

panel_a_path = (
    SUPP_TABLE_DIR /
    "Table_S6A_unadjusted_context_associations.csv"
)

panel_b_path = (
    SUPP_TABLE_DIR /
    "Table_S6B_adjusted_context_associations.csv"
)

panel_a.to_csv(panel_a_path, index=False)
panel_b.to_csv(panel_b_path, index=False)

# Generate LaTeX

latex_lines = []

latex_lines.append(r"\begin{table*}[t]")
latex_lines.append(
    r"\caption{Survey-weighted contextual associations with the "
    r"CReST transfer score. Panel A reports unadjusted system-equal "
    r"contrasts and Panel B reports adjusted associations together "
    r"with the stricter support-threshold sensitivity analysis.}"
)
latex_lines.append(r"\label{tab:supp_context_associations}")
latex_lines.append(r"\centering")
latex_lines.append(r"\scriptsize")
latex_lines.append(r"\renewcommand{\arraystretch}{1.10}")
latex_lines.append("")

# Panel A

latex_lines.append(
    r"\textbf{Panel A. Unadjusted survey-weighted contextual contrasts}"
)
latex_lines.append(r"\par\smallskip")

latex_lines.append(
    r"\begin{tabular}{@{}lrrrrrr@{}}"
)

latex_lines.append(r"\toprule")

latex_lines.append(
    r"\textbf{Contrast} & "
    r"\textbf{Systems} & "
    r"\textbf{Difference} & "
    r"\textbf{95\% CI} & "
    r"\textbf{Std. difference} & "
    r"\textbf{95\% CI} & "
    r"\textbf{Positive systems} \\"
)

latex_lines.append(r"\midrule")

for _, r in panel_a.iterrows():

    latex_lines.append(
        f"{r['contrast']} & "
        f"{int(r['n_systems'])} & "
        f"{r['country_equal_difference']:+.4f} & "
        f"[{r['system_boot_ci_low']:.4f}, "
        f"{r['system_boot_ci_high']:.4f}] & "
        f"{r['mean_standardized_difference']:+.3f} & "
        f"[{r['std_ci_low']:.3f}, "
        f"{r['std_ci_high']:.3f}] & "
        f"{int(r['positive_systems'])}/"
        f"{int(r['n_systems'])} \\\\"
    )

latex_lines.append(r"\bottomrule")
latex_lines.append(r"\end{tabular}")

latex_lines.append(r"\vspace{1em}")

# Panel B

latex_lines.append(
    r"\textbf{Panel B. Adjusted associations and support-threshold sensitivity}"
)

latex_lines.append(r"\par\smallskip")

latex_lines.append(
    r"\begin{tabular}{@{}lrrrrrr@{}}"
)

latex_lines.append(r"\toprule")

latex_lines.append(
    r"\textbf{Predictor} & "
    r"\textbf{$N_{\mathrm{sys}}$} & "
    r"\textbf{Primary estimate} & "
    r"\textbf{95\% CI} & "
    r"\textbf{Positive (\%)} & "
    r"\textbf{Sensitivity estimate} & "
    r"\textbf{95\% CI} \\"
)

latex_lines.append(r"\midrule")

for _, r in panel_b.iterrows():

    latex_lines.append(
        f"{r['Predictor']} & "
        f"{int(r['primary_n_systems'])} & "
        f"{r['primary_estimate']:+.4f} & "
        f"[{r['primary_ci_low']:.4f}, "
        f"{r['primary_ci_high']:.4f}] & "
        f"{r['pct_positive_systems']:.1f} & "
        f"{r['sensitivity_estimate']:+.4f} & "
        f"[{r['sensitivity_ci_low']:.4f}, "
        f"{r['sensitivity_ci_high']:.4f}] \\\\"
    )

latex_lines.append(r"\bottomrule")
latex_lines.append(r"\end{tabular}")

latex_lines.append("")

latex_lines.append(
    r"\begin{flushleft}"
    r"\footnotesize "
    r"\textit{Note.} The CReST transfer score is the average of the "
    r"A$\rightarrow$B and B$\rightarrow$A disjoint-item transfer "
    r"scores and is not an official PISA plausible value or proficiency "
    r"score. In Panel A, each contrast is defined as Group B minus "
    r"Group A: Q4 minus Q1 for home resources, repeated minus never "
    r"repeated, immigrant-background minus native, male minus female, "
    r"and home/test-language mismatch minus match. Estimates give equal "
    r"weight to education systems. Confidence intervals are "
    r"nonparametric system-bootstrap intervals. Standardised differences "
    r"are reported as a scale-free sensitivity description. In Panel B, "
    r"the primary adjusted analysis required a minimum supported sample "
    r"of 30 per included group or predictor configuration and retained "
    r"33 education systems; the sensitivity analysis increased this "
    r"threshold to 50 and retained 26 systems. Panel B confidence "
    r"intervals are also system-bootstrap intervals. Associations are "
    r"descriptive and should not be interpreted causally."
    r"\end{flushleft}"
)

latex_lines.append(r"\end{table*}")

latex_text = "\n".join(latex_lines)

tex_path = (
    SUPP_TABLE_DIR /
    "Table_S6_context_associations.tex"
)

tex_path.write_text(
    latex_text,
    encoding="utf-8"
)

print("\nSaved:")
print(panel_a_path)
print(panel_b_path)
print(tex_path)

print("\n" + "=" * 120)
print("LATEX PREVIEW")
print("=" * 120)
print(latex_text)

========================================================================================================================
SUPPLEMENTARY TABLE S6 - PANEL A
========================================================================================================================

,contrast,Direction,n_systems,country_equal_difference,system_boot_ci_low,system_boot_ci_high,mean_standardized_difference,std_ci_low,std_ci_high,positive_systems,negative_systems,positive_pct
0,Home resources,Q4_high $-$ Q1_low,63,0.105813,0.097659,0.113786,0.840888,0.778911,0.903400,63,0,100.0
1,Grade repetition,Repeated grade $-$ Never repeated,50,-0.101497,-0.111186,-0.091743,-0.795507,-0.868383,-0.723886,0,50,0.0
2,Immigrant background,Immigrant background $-$ Native,37,-0.011724,-0.028108,0.005834,-0.092379,-0.217199,0.040288,12,25,32.4
3,Gender,Male $-$ Female,63,-0.038623,-0.042514,-0.034865,-0.296964,-0.326907,-0.268511,0,63,0.0
4,Home/test language,Home/test language mismatch $-$ Home/test lang...,53,-0.033724,-0.049366,-0.015273,-0.256462,-0.378729,-0.115970,12,41,22.6

========================================================================================================================
SUPPLEMENTARY TABLE S6 - PANEL B
========================================================================================================================

,Predictor,primary_n_systems,primary_estimate,primary_ci_low,primary_ci_high,pct_positive_systems,sensitivity_n_systems,sensitivity_estimate,sensitivity_ci_low,sensitivity_ci_high,same_direction_supported_both,interpretation
0,Home-resource index (HOMEPOS),33,0.260477,0.236427,0.285028,100.0,26,0.239899,0.218823,0.262293,True,Robust positive association
1,Male,33,-0.273496,-0.313518,-0.237169,0.0,26,-0.273471,-0.316062,-0.232928,True,Robust negative association
2,Repeated grade,33,-0.588417,-0.652257,-0.527676,0.0,26,-0.578567,-0.651820,-0.507030,True,Robust negative association
3,Immigrant background,33,0.097839,0.005756,0.195777,60.6,26,0.129274,0.026278,0.242172,True,Positive conditional association; heterogeneou...
4,Home/test language mismatch,33,-0.102995,-0.208877,0.035164,15.2,26,-0.067601,-0.188432,0.102712,False,No robust cross-system adjusted association
5,Age,33,0.024158,0.016264,0.031819,81.8,26,0.022264,0.014009,0.030121,True,Small robust positive association

========================================================================================================================
INTEGRITY CHECKS
========================================================================================================================
Home resources            observed=+0.105813 expected=+0.105813 match=True
Grade repetition          observed=-0.101497 expected=-0.101497 match=True
Immigrant background      observed=-0.011724 expected=-0.011724 match=True
Gender                    observed=-0.038623 expected=-0.038623 match=True
Home/test language        observed=-0.033724 expected=-0.033724 match=True

Primary adjusted systems: [33]
Sensitivity adjusted systems: [26]

Saved:
PROJECT_ROOT\results\supplementary_material\tables\Table_S6A_unadjusted_context_associations.csv
PROJECT_ROOT\results\supplementary_material\tables\Table_S6B_adjusted_context_associations.csv
PROJECT_ROOT\results\supplementary_material\tables\Table_S6_context_associations.tex

========================================================================================================================
LATEX PREVIEW
========================================================================================================================
\begin{table*}[t]
\caption{Survey-weighted contextual associations with the CReST transfer score. Panel A reports unadjusted system-equal contrasts and Panel B reports adjusted associations together with the stricter support-threshold sensitivity analysis.}
\label{tab:supp_context_associations}
\centering
\scriptsize
\renewcommand{\arraystretch}{1.10}

\textbf{Panel A. Unadjusted survey-weighted contextual contrasts}
\par\smallskip
\begin{tabular}{@{}lrrrrrr@{}}
\toprule
\textbf{Contrast} & \textbf{Systems} & \textbf{Difference} & \textbf{95\% CI} & \textbf{Std. difference} & \textbf{95\% CI} & \textbf{Positive systems} \\
\midrule
Home resources & 63 & +0.1058 & [0.0977, 0.1138] & +0.841 & [0.779, 0.903] & 63/63 \\
Grade repetition & 50 & -0.1015 & [-0.1112, -0.0917] & -0.796 & [-0.868, -0.724] & 0/50 \\
Immigrant background & 37 & -0.0117 & [-0.0281, 0.0058] & -0.092 & [-0.217, 0.040] & 12/37 \\
Gender & 63 & -0.0386 & [-0.0425, -0.0349] & -0.297 & [-0.327, -0.269] & 0/63 \\
Home/test language & 53 & -0.0337 & [-0.0494, -0.0153] & -0.256 & [-0.379, -0.116] & 12/53 \\
\bottomrule
\end{tabular}
\vspace{1em}
\textbf{Panel B. Adjusted associations and support-threshold sensitivity}
\par\smallskip
\begin{tabular}{@{}lrrrrrr@{}}
\toprule
\textbf{Predictor} & \textbf{$N_{\mathrm{sys}}$} & \textbf{Primary estimate} & \textbf{95\% CI} & \textbf{Positive (\%)} & \textbf{Sensitivity estimate} & \textbf{95\% CI} \\
\midrule
Home-resource index (HOMEPOS) & 33 & +0.2605 & [0.2364, 0.2850] & 100.0 & +0.2399 & [0.2188, 0.2623] \\
Male & 33 & -0.2735 & [-0.3135, -0.2372] & 0.0 & -0.2735 & [-0.3161, -0.2329] \\
Repeated grade & 33 & -0.5884 & [-0.6523, -0.5277] & 0.0 & -0.5786 & [-0.6518, -0.5070] \\
Immigrant background & 33 & +0.0978 & [0.0058, 0.1958] & 60.6 & +0.1293 & [0.0263, 0.2422] \\
Home/test language mismatch & 33 & -0.1030 & [-0.2089, 0.0352] & 15.2 & -0.0676 & [-0.1884, 0.1027] \\
Age & 33 & +0.0242 & [0.0163, 0.0318] & 81.8 & +0.0223 & [0.0140, 0.0301] \\
\bottomrule
\end{tabular}

\begin{flushleft}\footnotesize \textit{Note.} The CReST transfer score is the average of the A$\rightarrow$B and B$\rightarrow$A disjoint-item transfer scores and is not an official PISA plausible value or proficiency score. In Panel A, each contrast is defined as Group B minus Group A: Q4 minus Q1 for home resources, repeated minus never repeated, immigrant-background minus native, male minus female, and home/test-language mismatch minus match. Estimates give equal weight to education systems. Confidence intervals are nonparametric system-bootstrap intervals. Standardised differences are reported as a scale-free sensitivity description. In Panel B, the primary adjusted analysis required a minimum supported sample of 30 per included group or predictor configuration and retained 33 education systems; the sensitivity analysis increased this threshold to 50 and retained 26 systems. Panel B confidence intervals are also system-bootstrap intervals. Associations are descriptive and should not be interpreted causally.\end{flushleft}
\end{table*}

In [ ]:
# Inspect official PISA Creative Thinking convergent-alignment outputs

survey_dir = RESULTS_DIR / "survey_weighted_population"

pisa_summary = pd.read_csv(
    survey_dir /
    "crest_convergent_validity_pisa_ct_summary.csv"
)

pisa_by_system = pd.read_csv(
    survey_dir /
    "crest_convergent_validity_pisa_ct_by_system.csv"
)

pisa_sensitivity = pd.read_csv(
    survey_dir /
    "crest_convergent_validity_sensitivity.csv"
)

pisa_influence = pd.read_csv(
    survey_dir /
    "crest_convergent_validity_system_influence.csv"
)

print("=" * 120)
print("A. CONVERGENT ALIGNMENT SUMMARY")
print("=" * 120)

print("Shape:", pisa_summary.shape)
print("Columns:", pisa_summary.columns.tolist())
display(pisa_summary)


print("\n" + "=" * 120)
print("B. BY-SYSTEM ALIGNMENT")
print("=" * 120)

print("Shape:", pisa_by_system.shape)
print("Columns:", pisa_by_system.columns.tolist())
display(pisa_by_system.head(20))


print("\n" + "=" * 120)
print("C. SENSITIVITY ANALYSIS")
print("=" * 120)

print("Shape:", pisa_sensitivity.shape)
print("Columns:", pisa_sensitivity.columns.tolist())
display(pisa_sensitivity)


print("\n" + "=" * 120)
print("D. SYSTEM-INFLUENCE ANALYSIS")
print("=" * 120)

print("Shape:", pisa_influence.shape)
print("Columns:", pisa_influence.columns.tolist())
display(pisa_influence.head(20))

In [ ]:
# Build Supplementary Table S7:
# Convergent alignment with official PISA Creative Thinking proficiency

import pandas as pd
import numpy as np

survey_dir = RESULTS_DIR / "survey_weighted_population"

# Load locked outputs

pisa_summary = pd.read_csv(
    survey_dir /
    "crest_convergent_validity_pisa_ct_summary.csv"
)

pisa_by_system = pd.read_csv(
    survey_dir /
    "crest_convergent_validity_pisa_ct_by_system.csv"
)

pisa_sensitivity = pd.read_csv(
    survey_dir /
    "crest_convergent_validity_sensitivity.csv"
)

pisa_influence = pd.read_csv(
    survey_dir /
    "crest_convergent_validity_system_influence.csv"
)

# Primary and sensitivity rows

primary = pisa_sensitivity.loc[
    pisa_sensitivity["analysis"] == "Primary: all systems"
].iloc[0]

sensitivity = pisa_sensitivity.loc[
    pisa_sensitivity["analysis"] == "Sensitivity: exclude TAP and MAC"
].iloc[0]

summary = pisa_summary.iloc[0]

# Table S7

table_s7 = pd.DataFrame([
    {
        "Analysis": "Primary: all systems",
        "Systems": int(primary["n_systems"]),
        "Mean r": primary["mean_r"],
        "Median r": primary["median_r"],
        "95% CI low": primary["ci_low"],
        "95% CI high": primary["ci_high"],
        "r > 0.50": int(primary["systems_r_gt_050"]),
        "r > 0.60": int(primary["systems_r_gt_060"]),
        "r > 0.70": int(primary["systems_r_gt_070"]),
    },
    {
        "Analysis": "Sensitivity: excluding TAP and MAC",
        "Systems": int(sensitivity["n_systems"]),
        "Mean r": sensitivity["mean_r"],
        "Median r": sensitivity["median_r"],
        "95% CI low": sensitivity["ci_low"],
        "95% CI high": sensitivity["ci_high"],
        "r > 0.50": int(sensitivity["systems_r_gt_050"]),
        "r > 0.60": int(sensitivity["systems_r_gt_060"]),
        "r > 0.70": int(sensitivity["systems_r_gt_070"]),
    },
])

print("=" * 120)
print("SUPPLEMENTARY TABLE S7")
print("=" * 120)

display(
    table_s7.round({
        "Mean r": 6,
        "Median r": 6,
        "95% CI low": 6,
        "95% CI high": 6,
    })
)

# Additional distribution / influence audit

lowest = pisa_by_system.nsmallest(5, "correlation")[
    ["country", "n_students", "correlation"]
]

highest = pisa_by_system.nlargest(5, "correlation")[
    ["country", "n_students", "correlation"]
]

top_influence = pisa_influence.nlargest(
    5,
    "absolute_influence"
)[
    [
        "country",
        "system_r",
        "change_in_mean_if_removed",
        "absolute_influence",
    ]
]

print("\n" + "=" * 120)
print("PRIMARY DISTRIBUTION AUDIT")
print("=" * 120)

print(f"Between-system SD : {summary['between_system_sd']:.6f}")
print(f"Minimum r         : {summary['minimum_r']:.6f}")
print(f"Maximum r         : {summary['maximum_r']:.6f}")
print(f"10% trimmed mean  : {summary['trimmed_mean_r_10pct']:.6f}")

print("\nLowest five systems:")
display(lowest.round(6))

print("\nHighest five systems:")
display(highest.round(6))

print("\nMost influential systems:")
display(top_influence.round(6))

# Integrity checks

print("\n" + "=" * 120)
print("INTEGRITY CHECKS")
print("=" * 120)

print(
    "Primary mean matches summary:",
    np.isclose(
        primary["mean_r"],
        summary["mean_r"],
        atol=1e-12
    )
)

print(
    "Primary median matches summary:",
    np.isclose(
        primary["median_r"],
        summary["median_r"],
        atol=1e-12
    )
)

print(
    "Systems > .60:",
    int(primary["systems_r_gt_060"])
)

print(
    "Systems > .70:",
    int(primary["systems_r_gt_070"])
)

print(
    "Sensitivity mean excluding TAP/MAC:",
    f"{sensitivity['mean_r']:.6f}"
)

# Save CSV

csv_path = (
    SUPP_TABLE_DIR /
    "Table_S7_pisa_ct_convergent_alignment.csv"
)

table_s7.to_csv(csv_path, index=False)

# Generate LaTeX

latex_lines = []

latex_lines.append(r"\begin{table*}[t]")
latex_lines.append(
    r"\caption{Convergent alignment between the CReST transfer score "
    r"and official PISA 2022 Creative Thinking proficiency across "
    r"education systems.}"
)
latex_lines.append(r"\label{tab:supp_pisa_alignment}")
latex_lines.append(r"\centering")
latex_lines.append(r"\small")
latex_lines.append(r"\renewcommand{\arraystretch}{1.10}")
latex_lines.append(r"\setlength{\tabcolsep}{6pt}")
latex_lines.append("")

latex_lines.append(
    r"\begin{tabular}{@{}lrrrrrrrr@{}}"
)
latex_lines.append(r"\toprule")

latex_lines.append(
    r"\textbf{Analysis} & "
    r"\textbf{Systems} & "
    r"\textbf{Mean $r$} & "
    r"\textbf{Median $r$} & "
    r"\textbf{95\% CI} & "
    r"\textbf{$r>.50$} & "
    r"\textbf{$r>.60$} & "
    r"\textbf{$r>.70$} \\"
)

latex_lines.append(r"\midrule")

for _, r in table_s7.iterrows():

    latex_lines.append(
        f"{r['Analysis']} & "
        f"{int(r['Systems'])} & "
        f"{r['Mean r']:.4f} & "
        f"{r['Median r']:.4f} & "
        f"[{r['95% CI low']:.4f}, {r['95% CI high']:.4f}] & "
        f"{int(r['r > 0.50'])} & "
        f"{int(r['r > 0.60'])} & "
        f"{int(r['r > 0.70'])} \\\\"
    )

latex_lines.append(r"\bottomrule")
latex_lines.append(r"\end{tabular}")

latex_lines.append("")
latex_lines.append(
    r"\begin{flushleft}"
    r"\footnotesize "
    r"\textit{Note.} Alignment was evaluated between the survey-weighted "
    r"CReST disjoint-item transfer score and official PISA 2022 Creative "
    r"Thinking proficiency represented by all 10 plausible values. "
    r"Correlations were combined within each education system using the "
    r"plausible-value and replicate-weight procedure before system-level "
    r"summaries were calculated. Reported confidence intervals are "
    r"nonparametric system-bootstrap intervals. In the primary analysis, "
    r"the system-equal mean correlation was 0.7528 "
    r"(95\% CI [0.7266, 0.7731]); 61 of 63 systems exceeded 0.60 and "
    r"54 exceeded 0.70. TAP and MAC showed substantially lower "
    r"correlations than the remaining systems. Excluding these two "
    r"systems increased the system-equal mean to 0.7681 without changing "
    r"the substantive conclusion. The analysis is interpreted as "
    r"convergent alignment rather than external validation because both "
    r"quantities are derived from the same PISA 2022 assessment."
    r"\end{flushleft}"
)

latex_lines.append(r"\end{table*}")

latex_text = "\n".join(latex_lines)

tex_path = (
    SUPP_TABLE_DIR /
    "Table_S7_pisa_ct_convergent_alignment.tex"
)

tex_path.write_text(
    latex_text,
    encoding="utf-8"
)

print("\nSaved CSV:")
print(csv_path)

print("\nSaved LaTeX:")
print(tex_path)

print("\n" + "=" * 120)
print("LATEX PREVIEW")
print("=" * 120)
print(latex_text)

========================================================================================================================
SUPPLEMENTARY TABLE S7
========================================================================================================================

                             Analysis  Systems    Mean r  Median r  95% CI low  95% CI high  r > 0.50  r > 0.60  r > 0.70
0                Primary: all systems       63  0.752801   0.77313    0.726554     0.773143        61        61        54
1  Sensitivity: excluding TAP and MAC       61  0.768087   0.77363    0.756585     0.779084        61        61        54

========================================================================================================================
PRIMARY DISTRIBUTION AUDIT
========================================================================================================================
Between-system SD : 0.096534
Minimum r         : 0.229569
Maximum r         : 0.836044
10% trimmed mean  : 0.767741

Lowest five systems:

  country  n_students  correlation
0     TAP        1569     0.229569
1     MAC        1227     0.343581
2     LVA        1516     0.671442
3     KOR        1783     0.672666
4     UZB        1988     0.677013

Highest five systems:

   country  n_students  correlation
62     PHL        1940     0.836044
61     MKD        1756     0.833650
60     SVK        1563     0.832856
59     ROU        2005     0.832556
58     QAT        2093     0.830676

Most influential systems:

  country  system_r  change_in_mean_if_removed  absolute_influence
0     TAP  0.229569                   0.008439            0.008439
1     MAC  0.343581                   0.006600            0.006600
2     PHL  0.836044                  -0.001343            0.001343
3     LVA  0.671442                   0.001312            0.001312
4     MKD  0.833650                  -0.001304            0.001304

========================================================================================================================
INTEGRITY CHECKS
========================================================================================================================
Primary mean matches summary: True
Primary median matches summary: True
Systems > .60: 61
Systems > .70: 54
Sensitivity mean excluding TAP/MAC: 0.768087

Saved CSV:
PROJECT_ROOT\results\supplementary_material\tables\Table_S7_pisa_ct_convergent_alignment.csv

Saved LaTeX:
PROJECT_ROOT\results\supplementary_material\tables\Table_S7_pisa_ct_convergent_alignment.tex

========================================================================================================================
LATEX PREVIEW
========================================================================================================================
\begin{table*}[t]
\caption{Convergent alignment between the CReST transfer score and official PISA 2022 Creative Thinking proficiency across education systems.}
\label{tab:supp_pisa_alignment}
\centering
\small
\renewcommand{\arraystretch}{1.10}
\setlength{\tabcolsep}{6pt}

\begin{tabular}{@{}lrrrrrrrr@{}}
\toprule
\textbf{Analysis} & \textbf{Systems} & \textbf{Mean $r$} & \textbf{Median $r$} & \textbf{95\% CI} & \textbf{$r>.50$} & \textbf{$r>.60$} & \textbf{$r>.70$} \\
\midrule
Primary: all systems & 63 & 0.7528 & 0.7731 & [0.7266, 0.7731] & 61 & 61 & 54 \\
Sensitivity: excluding TAP and MAC & 61 & 0.7681 & 0.7736 & [0.7566, 0.7791] & 61 & 61 & 54 \\
\bottomrule
\end{tabular}

\begin{flushleft}\footnotesize \textit{Note.} Alignment was evaluated between the survey-weighted CReST disjoint-item transfer score and official PISA 2022 Creative Thinking proficiency represented by all 10 plausible values. Correlations were combined within each education system using the plausible-value and replicate-weight procedure before system-level summaries were calculated. Reported confidence intervals are nonparametric system-bootstrap intervals. In the primary analysis, the system-equal mean correlation was 0.7528 (95\% CI [0.7266, 0.7731]); 61 of 63 systems exceeded 0.60 and 54 exceeded 0.70. TAP and MAC showed substantially lower correlations than the remaining systems. Excluding these two systems increased the system-equal mean to 0.7681 without changing the substantive conclusion. The analysis is interpreted as convergent alignment rather than external validation because both quantities are derived from the same PISA 2022 assessment.\end{flushleft}
\end{table*}

In [ ]:
# Locate profile-structure, clustering, axis-stability,
# and final sensitivity result files

from pathlib import Path

keywords = [
    "profile",
    "cluster",
    "axis",
    "stability",
    "sensitivity",
    "gaussian",
    "null",
]

matches = []

for p in RESULTS_DIR.rglob("*"):
    if p.is_file():
        name_lower = p.name.lower()

        if any(k in name_lower for k in keywords):
            matches.append(
                str(p.relative_to(BASE_DIR))
            )

print("=" * 120)
print("PROFILE / CLUSTERING / STABILITY / SENSITIVITY FILES")
print("=" * 120)

for m in sorted(matches):
    print(m)

print("\nTotal candidate files:", len(matches))

In [ ]:
# Inspect profile structure, clustering safeguard,
# and continuous-axis stability outputs

import json
import pandas as pd

PROFILE_DIR = RESULTS_DIR / "crosssystem_profile_stability"

# Load key files

cluster_candidates = pd.read_csv(
    PROFILE_DIR /
    "crest_profile_cluster_candidate_stability.csv"
)

gaussian_null = pd.read_csv(
    PROFILE_DIR /
    "crest_k2_matched_gaussian_null.csv"
)

axis_loadings = pd.read_csv(
    PROFILE_DIR /
    "crest_continuous_profile_axis_loadings.csv"
)

pv_stability = pd.read_csv(
    PROFILE_DIR /
    "crest_continuous_profile_pv_stability.csv"
)

crosssystem_axis_summary = pd.read_csv(
    PROFILE_DIR /
    "crest_continuous_profile_axes_63system_summary.csv"
)

profile_geometry = pd.read_csv(
    PROFILE_DIR /
    "crest_profile_geometry_by_pv.csv"
)

with open(
    PROFILE_DIR /
    "crest_crosssystem_profile_findings_LOCKED.json",
    "r",
    encoding="utf-8"
) as f:
    locked_profile = json.load(f)


# A. Cluster candidates

print("=" * 120)
print("A. CLUSTER-CANDIDATE STABILITY")
print("=" * 120)

print("Shape:", cluster_candidates.shape)
print("Columns:", cluster_candidates.columns.tolist())
display(cluster_candidates)


# B. Gaussian-null safeguard

print("\n" + "=" * 120)
print("B. MATCHED GAUSSIAN-NULL SAFEGUARD")
print("=" * 120)

print("Shape:", gaussian_null.shape)
print("Columns:", gaussian_null.columns.tolist())
display(gaussian_null)


# C. Continuous profile axis loadings

print("\n" + "=" * 120)
print("C. CONTINUOUS PROFILE AXIS LOADINGS")
print("=" * 120)

print("Shape:", axis_loadings.shape)
print("Columns:", axis_loadings.columns.tolist())
display(axis_loadings)


# D. Plausible-value axis stability

print("\n" + "=" * 120)
print("D. PLAUSIBLE-VALUE AXIS STABILITY")
print("=" * 120)

print("Shape:", pv_stability.shape)
print("Columns:", pv_stability.columns.tolist())
display(pv_stability)


# E. Cross-system axis stability

print("\n" + "=" * 120)
print("E. CROSS-SYSTEM AXIS STABILITY SUMMARY")
print("=" * 120)

print("Shape:", crosssystem_axis_summary.shape)
print("Columns:", crosssystem_axis_summary.columns.tolist())
display(crosssystem_axis_summary)


# F. Profile geometry by plausible value

print("\n" + "=" * 120)
print("F. PROFILE GEOMETRY BY PLAUSIBLE VALUE")
print("=" * 120)

print("Shape:", profile_geometry.shape)
print("Columns:", profile_geometry.columns.tolist())
display(profile_geometry)


# G. Locked findings

print("\n" + "=" * 120)
print("G. LOCKED PROFILE FINDINGS")
print("=" * 120)

print(json.dumps(
    locked_profile,
    indent=2,
    ensure_ascii=False
))

In [ ]:
# Build Supplementary Table S8:
# Profile structure, clustering safeguard, and axis stability

import json
import numpy as np
import pandas as pd

PROFILE_DIR = RESULTS_DIR / "crosssystem_profile_stability"

# Load source files

cluster_candidates = pd.read_csv(
    PROFILE_DIR /
    "crest_profile_cluster_candidate_stability.csv"
)

gaussian_null = pd.read_csv(
    PROFILE_DIR /
    "crest_k2_matched_gaussian_null.csv"
)

axis_loadings = pd.read_csv(
    PROFILE_DIR /
    "crest_continuous_profile_axis_loadings.csv"
)

pv_stability = pd.read_csv(
    PROFILE_DIR /
    "crest_continuous_profile_pv_stability.csv"
)

crosssystem_axes = pd.read_csv(
    PROFILE_DIR /
    "crest_continuous_profile_axes_63system_summary.csv"
)

with open(
    PROFILE_DIR /
    "crest_crosssystem_profile_findings_LOCKED.json",
    "r",
    encoding="utf-8"
) as f:
    locked_profile = json.load(f)

# PANEL A - Cluster-candidate stability

panel_a = cluster_candidates[
    [
        "k",
        "silhouette_mean",
        "pv_ari_mean",
        "resample_ari_mean",
        "system_ari_mean",
        "minimum_cluster_share_mean",
    ]
].copy()

panel_a = panel_a.rename(
    columns={
        "k": "k",
        "silhouette_mean": "Silhouette",
        "pv_ari_mean": "PV ARI",
        "resample_ari_mean": "Resampling ARI",
        "system_ari_mean": "System ARI",
        "minimum_cluster_share_mean": "Minimum cluster share",
    }
)

# PANEL B - Matched Gaussian-null safeguard

guard = locked_profile["clustering_safeguard"]

panel_b = pd.DataFrame([
    {
        "Metric": "Mean silhouette",
        "Observed": guard["observed_mean_silhouette"],
        "Matched Gaussian null": guard["matched_gaussian_mean_silhouette"],
        "Observed - null":
            guard["observed_mean_silhouette"]
            - guard["matched_gaussian_mean_silhouette"],
    },
    {
        "Metric": "Mean centroid separation",
        "Observed": guard["observed_mean_separation"],
        "Matched Gaussian null": guard["matched_gaussian_mean_separation"],
        "Observed - null":
            guard["observed_mean_separation"]
            - guard["matched_gaussian_mean_separation"],
    },
])

# PANEL C1 - Continuous dimension loadings

variance_d1 = locked_profile["dimension_1"]["variance_share_percent"]
variance_d2 = locked_profile["dimension_2"]["variance_share_percent"]

panel_c_loadings = axis_loadings.copy()

panel_c_loadings = panel_c_loadings.rename(
    columns={
        "domain": "Domain",
        "dimension_1_loading": "Dimension 1 loading",
        "dimension_2_loading": "Dimension 2 loading",
    }
)

# PANEL C2 - Stability summary

pv_mean_cosine = locked_profile["pv_axis_stability"]["mean_cosine"]
pv_max_angle = locked_profile["pv_axis_stability"]["maximum_angle_degrees"]

system_mean_cosine = locked_profile[
    "cross_system_axis_stability"
]["mean_cosine"]

system_median_cosine = locked_profile[
    "cross_system_axis_stability"
]["median_cosine"]

system_mean_angle = locked_profile[
    "cross_system_axis_stability"
]["mean_angle_degrees"]

system_max_mean_angle = locked_profile[
    "cross_system_axis_stability"
]["maximum_mean_angle_degrees"]

panel_c_stability = pd.DataFrame([
    {
        "Stability assessment": "Across 10 plausible values",
        "Mean cosine": pv_mean_cosine,
        "Median cosine": np.nan,
        "Mean angle (deg)": np.nan,
        "Maximum angle / mean angle (deg)": pv_max_angle,
    },
    {
        "Stability assessment": "Across 63 education systems",
        "Mean cosine": system_mean_cosine,
        "Median cosine": system_median_cosine,
        "Mean angle (deg)": system_mean_angle,
        "Maximum angle / mean angle (deg)": system_max_mean_angle,
    },
])

# Display

print("=" * 120)
print("SUPPLEMENTARY TABLE S8 - PANEL A")
print("=" * 120)

display(
    panel_a.round({
        "Silhouette": 4,
        "PV ARI": 4,
        "Resampling ARI": 4,
        "System ARI": 4,
        "Minimum cluster share": 4,
    })
)

print("\n" + "=" * 120)
print("SUPPLEMENTARY TABLE S8 - PANEL B")
print("=" * 120)

display(
    panel_b.round({
        "Observed": 6,
        "Matched Gaussian null": 6,
        "Observed - null": 6,
    })
)

print("\n" + "=" * 120)
print("SUPPLEMENTARY TABLE S8 - PANEL C1")
print("=" * 120)

display(
    panel_c_loadings.round({
        "Dimension 1 loading": 6,
        "Dimension 2 loading": 6,
    })
)

print(
    f"\nDimension 1 variance share: {variance_d1:.4f}%"
)
print(
    f"Dimension 2 variance share: {variance_d2:.4f}%"
)

print("\n" + "=" * 120)
print("SUPPLEMENTARY TABLE S8 - PANEL C2")
print("=" * 120)

display(
    panel_c_stability.round({
        "Mean cosine": 6,
        "Median cosine": 6,
        "Mean angle (deg)": 3,
        "Maximum angle / mean angle (deg)": 3,
    })
)

# Integrity checks

k2 = panel_a.loc[panel_a["k"] == 2].iloc[0]

print("\n" + "=" * 120)
print("INTEGRITY CHECKS")
print("=" * 120)

print(
    f"k=2 silhouette             : {k2['Silhouette']:.6f}"
)

print(
    f"k=2 PV ARI                 : {k2['PV ARI']:.6f}"
)

print(
    f"k=2 resampling ARI         : {k2['Resampling ARI']:.6f}"
)

print(
    f"k=2 system ARI             : {k2['System ARI']:.6f}"
)

print(
    f"Gaussian safeguard observed: "
    f"{guard['observed_mean_silhouette']:.6f}"
)

print(
    f"Gaussian safeguard null    : "
    f"{guard['matched_gaussian_mean_silhouette']:.6f}"
)

print(
    "Null silhouette >= observed:",
    guard["matched_gaussian_mean_silhouette"]
    >= guard["observed_mean_silhouette"]
)

print(
    "Null separation >= observed:",
    guard["matched_gaussian_mean_separation"]
    >= guard["observed_mean_separation"]
)

print(
    f"PV mean cosine             : {pv_mean_cosine:.6f}"
)

print(
    f"Cross-system mean cosine   : {system_mean_cosine:.6f}"
)

# Save CSV outputs

panel_a_path = (
    SUPP_TABLE_DIR /
    "Table_S8A_cluster_candidate_stability.csv"
)

panel_b_path = (
    SUPP_TABLE_DIR /
    "Table_S8B_gaussian_null_safeguard.csv"
)

panel_c1_path = (
    SUPP_TABLE_DIR /
    "Table_S8C_continuous_axis_loadings.csv"
)

panel_c2_path = (
    SUPP_TABLE_DIR /
    "Table_S8D_axis_stability.csv"
)

panel_a.to_csv(panel_a_path, index=False)
panel_b.to_csv(panel_b_path, index=False)
panel_c_loadings.to_csv(panel_c1_path, index=False)
panel_c_stability.to_csv(panel_c2_path, index=False)

# Generate LaTeX Table S8

latex_lines = []

latex_lines.append(r"\begin{table*}[t]")
latex_lines.append(
    r"\caption{Profile-structure diagnostics, clustering safeguard, "
    r"and stability of the continuous domain-relative CReST profile space.}"
)
latex_lines.append(r"\label{tab:supp_profile_structure}")
latex_lines.append(r"\centering")
latex_lines.append(r"\scriptsize")
latex_lines.append(r"\renewcommand{\arraystretch}{1.10}")
latex_lines.append("")

# Panel A

latex_lines.append(
    r"\textbf{Panel A. Stability of candidate $k$-means solutions}"
)
latex_lines.append(r"\par\smallskip")

latex_lines.append(
    r"\begin{tabular}{@{}rrrrrr@{}}"
)

latex_lines.append(r"\toprule")

latex_lines.append(
    r"\textbf{$k$} & "
    r"\textbf{Silhouette} & "
    r"\textbf{PV ARI} & "
    r"\textbf{Resampling ARI} & "
    r"\textbf{System ARI} & "
    r"\textbf{Minimum cluster share} \\"
)

latex_lines.append(r"\midrule")

for _, r in panel_a.iterrows():
    latex_lines.append(
        f"{int(r['k'])} & "
        f"{r['Silhouette']:.4f} & "
        f"{r['PV ARI']:.4f} & "
        f"{r['Resampling ARI']:.4f} & "
        f"{r['System ARI']:.4f} & "
        f"{r['Minimum cluster share']:.4f} \\\\"
    )

latex_lines.append(r"\bottomrule")
latex_lines.append(r"\end{tabular}")

latex_lines.append(r"\vspace{1em}")

# Panel B

latex_lines.append(
    r"\textbf{Panel B. Matched unimodal Gaussian safeguard for the "
    r"$k=2$ solution}"
)
latex_lines.append(r"\par\smallskip")

latex_lines.append(
    r"\begin{tabular}{@{}lrrr@{}}"
)

latex_lines.append(r"\toprule")

latex_lines.append(
    r"\textbf{Metric} & "
    r"\textbf{Observed} & "
    r"\textbf{Matched Gaussian null} & "
    r"\textbf{Observed $-$ null} \\"
)

latex_lines.append(r"\midrule")

for _, r in panel_b.iterrows():
    latex_lines.append(
        f"{r['Metric']} & "
        f"{r['Observed']:.4f} & "
        f"{r['Matched Gaussian null']:.4f} & "
        f"{r['Observed - null']:+.4f} \\\\"
    )

latex_lines.append(r"\bottomrule")
latex_lines.append(r"\end{tabular}")

latex_lines.append(r"\vspace{1em}")

# Panel C

latex_lines.append(
    r"\textbf{Panel C. Continuous domain-relative profile dimensions}"
)
latex_lines.append(r"\par\smallskip")

latex_lines.append(
    r"\begin{tabular}{@{}lrr@{}}"
)

latex_lines.append(r"\toprule")

latex_lines.append(
    r"\textbf{Domain} & "
    r"\textbf{Dimension 1 loading} & "
    r"\textbf{Dimension 2 loading} \\"
)

latex_lines.append(r"\midrule")

for _, r in panel_c_loadings.iterrows():
    latex_lines.append(
        f"{r['Domain']} & "
        f"{r['Dimension 1 loading']:+.4f} & "
        f"{r['Dimension 2 loading']:+.4f} \\\\"
    )

latex_lines.append(r"\midrule")

latex_lines.append(
    f"Variance explained (\\%) & "
    f"{variance_d1:.2f} & "
    f"{variance_d2:.2f} \\\\"
)

latex_lines.append(r"\bottomrule")
latex_lines.append(r"\end{tabular}")

latex_lines.append(r"\vspace{1em}")

# Panel D

latex_lines.append(
    r"\textbf{Panel D. Stability of the continuous profile axes}"
)
latex_lines.append(r"\par\smallskip")

latex_lines.append(
    r"\begin{tabular}{@{}lrrrr@{}}"
)

latex_lines.append(r"\toprule")

latex_lines.append(
    r"\textbf{Assessment} & "
    r"\textbf{Mean cosine} & "
    r"\textbf{Median cosine} & "
    r"\textbf{Mean angle ($^\circ$)} & "
    r"\textbf{Maximum angle ($^\circ$)} \\"
)

latex_lines.append(r"\midrule")

latex_lines.append(
    f"Across 10 plausible values & "
    f"{pv_mean_cosine:.6f} & "
    f"-- & "
    f"-- & "
    f"{pv_max_angle:.3f} \\\\"
)

latex_lines.append(
    f"Across 63 education systems & "
    f"{system_mean_cosine:.6f} & "
    f"{system_median_cosine:.6f} & "
    f"{system_mean_angle:.3f} & "
    f"{system_max_mean_angle:.3f} \\\\"
)

latex_lines.append(r"\bottomrule")
latex_lines.append(r"\end{tabular}")

# Note

latex_lines.append("")
latex_lines.append(
    r"\begin{flushleft}"
    r"\footnotesize "
    r"\textit{Note.} ARI denotes adjusted Rand index. "
    r"Although the $k=2$ solution showed the strongest overall "
    r"stability among the candidate partitions, the matched unimodal "
    r"Gaussian safeguard produced both a higher mean silhouette "
    r"(0.3832 vs.\ 0.3695) and greater centroid separation "
    r"(1.8137 vs.\ 1.7618). Therefore, the stable $k=2$ partition "
    r"was not interpreted as evidence for discrete learner types. "
    r"Instead, the profile structure was retained as a continuous "
    r"two-dimensional zero-sum domain-relative space. Dimension 1 "
    r"represents Social-relative strength and explains 70.90\% of "
    r"the non-zero profile variance; Dimension 2 represents a "
    r"Written--Scientific contrast and explains 29.10\%. "
    r"Axis orientations were highly stable across the 10 plausible "
    r"values and across education systems."
    r"\end{flushleft}"
)

latex_lines.append(r"\end{table*}")

latex_text = "\n".join(latex_lines)

tex_path = (
    SUPP_TABLE_DIR /
    "Table_S8_profile_structure_and_stability.tex"
)

tex_path.write_text(
    latex_text,
    encoding="utf-8"
)

print("\nSaved:")
print(panel_a_path)
print(panel_b_path)
print(panel_c1_path)
print(panel_c2_path)
print(tex_path)

print("\n" + "=" * 120)
print("LATEX PREVIEW")
print("=" * 120)
print(latex_text)

========================================================================================================================
SUPPLEMENTARY TABLE S8 - PANEL A
========================================================================================================================

   k  Silhouette  PV ARI  Resampling ARI  System ARI  Minimum cluster share
0  2      0.3707  0.9073          0.9653      0.8001                 0.4963
1  3      0.3394  0.8888          0.9084      0.5420                 0.2533
2  4      0.3490  0.8722          0.9642      0.6847                 0.1858
3  5      0.3310  0.8254          0.8966      0.5062                 0.1448

========================================================================================================================
SUPPLEMENTARY TABLE S8 - PANEL B
========================================================================================================================

                     Metric  Observed  Matched Gaussian null  Observed - null
0           Mean silhouette  0.369484               0.383221        -0.013738
1  Mean centroid separation  1.761826               1.813721        -0.051895

========================================================================================================================
SUPPLEMENTARY TABLE S8 - PANEL C1
========================================================================================================================

       Domain  Dimension 1 loading  Dimension 2 loading
0     Written            -0.258494             0.774498
1      Social             0.799982            -0.163387
2  Scientific            -0.541489            -0.611111

Dimension 1 variance share: 70.8967%
Dimension 2 variance share: 29.1033%

========================================================================================================================
SUPPLEMENTARY TABLE S8 - PANEL C2
========================================================================================================================

          Stability assessment  Mean cosine  Median cosine  Mean angle (deg)  Maximum angle / mean angle (deg)
0   Across 10 plausible values     0.999989            NaN               NaN                             0.518
1  Across 63 education systems     0.988693       0.995333             6.899                            28.757

========================================================================================================================
INTEGRITY CHECKS
========================================================================================================================
k=2 silhouette             : 0.370723
k=2 PV ARI                 : 0.907252
k=2 resampling ARI         : 0.965284
k=2 system ARI             : 0.800121
Gaussian safeguard observed: 0.369484
Gaussian safeguard null    : 0.383221
Null silhouette >= observed: True
Null separation >= observed: True
PV mean cosine             : 0.999989
Cross-system mean cosine   : 0.988693

Saved:
PROJECT_ROOT\results\supplementary_material\tables\Table_S8A_cluster_candidate_stability.csv
PROJECT_ROOT\results\supplementary_material\tables\Table_S8B_gaussian_null_safeguard.csv
PROJECT_ROOT\results\supplementary_material\tables\Table_S8C_continuous_axis_loadings.csv
PROJECT_ROOT\results\supplementary_material\tables\Table_S8D_axis_stability.csv
PROJECT_ROOT\results\supplementary_material\tables\Table_S8_profile_structure_and_stability.tex

========================================================================================================================
LATEX PREVIEW
========================================================================================================================
\begin{table*}[t]
\caption{Profile-structure diagnostics, clustering safeguard, and stability of the continuous domain-relative CReST profile space.}
\label{tab:supp_profile_structure}
\centering
\scriptsize
\renewcommand{\arraystretch}{1.10}

\textbf{Panel A. Stability of candidate $k$-means solutions}
\par\smallskip
\begin{tabular}{@{}rrrrrr@{}}
\toprule
\textbf{$k$} & \textbf{Silhouette} & \textbf{PV ARI} & \textbf{Resampling ARI} & \textbf{System ARI} & \textbf{Minimum cluster share} \\
\midrule
2 & 0.3707 & 0.9073 & 0.9653 & 0.8001 & 0.4963 \\
3 & 0.3394 & 0.8888 & 0.9084 & 0.5420 & 0.2533 \\
4 & 0.3490 & 0.8722 & 0.9642 & 0.6847 & 0.1858 \\
5 & 0.3310 & 0.8254 & 0.8966 & 0.5062 & 0.1448 \\
\bottomrule
\end{tabular}
\vspace{1em}
\textbf{Panel B. Matched unimodal Gaussian safeguard for the $k=2$ solution}
\par\smallskip
\begin{tabular}{@{}lrrr@{}}
\toprule
\textbf{Metric} & \textbf{Observed} & \textbf{Matched Gaussian null} & \textbf{Observed $-$ null} \\
\midrule
Mean silhouette & 0.3695 & 0.3832 & -0.0137 \\
Mean centroid separation & 1.7618 & 1.8137 & -0.0519 \\
\bottomrule
\end{tabular}
\vspace{1em}
\textbf{Panel C. Continuous domain-relative profile dimensions}
\par\smallskip
\begin{tabular}{@{}lrr@{}}
\toprule
\textbf{Domain} & \textbf{Dimension 1 loading} & \textbf{Dimension 2 loading} \\
\midrule
Written & -0.2585 & +0.7745 \\
Social & +0.8000 & -0.1634 \\
Scientific & -0.5415 & -0.6111 \\
\midrule
Variance explained (\%) & 70.90 & 29.10 \\
\bottomrule
\end{tabular}
\vspace{1em}
\textbf{Panel D. Stability of the continuous profile axes}
\par\smallskip
\begin{tabular}{@{}lrrrr@{}}
\toprule
\textbf{Assessment} & \textbf{Mean cosine} & \textbf{Median cosine} & \textbf{Mean angle ($^\circ$)} & \textbf{Maximum angle ($^\circ$)} \\
\midrule
Across 10 plausible values & 0.999989 & -- & -- & 0.518 \\
Across 63 education systems & 0.988693 & 0.995333 & 6.899 & 28.757 \\
\bottomrule
\end{tabular}

\begin{flushleft}\footnotesize \textit{Note.} ARI denotes adjusted Rand index. Although the $k=2$ solution showed the strongest overall stability among the candidate partitions, the matched unimodal Gaussian safeguard produced both a higher mean silhouette (0.3832 vs.\ 0.3695) and greater centroid separation (1.8137 vs.\ 1.7618). Therefore, the stable $k=2$ partition was not interpreted as evidence for discrete learner types. Instead, the profile structure was retained as a continuous two-dimensional zero-sum domain-relative space. Dimension 1 represents Social-relative strength and explains 70.90\% of the non-zero profile variance; Dimension 2 represents a Written--Scientific contrast and explains 29.10\%. Axis orientations were highly stable across the 10 plausible values and across education systems.\end{flushleft}
\end{table*}

In [ ]:
# Inspect final sensitivity and robustness outputs

import json
import pandas as pd

SENS_DIR = RESULTS_DIR / "final_sensitivity_robustness"

combined_loadings = pd.read_csv(
    SENS_DIR /
    "combined_representation_axis_loadings.csv"
)

combined_pv_stability = pd.read_csv(
    SENS_DIR /
    "combined_representation_pv_axis_stability.csv"
)

both_direction_loadings = pd.read_csv(
    SENS_DIR /
    "both_direction_axis_loadings.csv"
)

both_direction_pv_stability = pd.read_csv(
    SENS_DIR /
    "both_direction_pv_axis_stability.csv"
)

four_domain_loadings = pd.read_csv(
    SENS_DIR /
    "four_domain_expanded_axis_loadings.csv"
)

four_domain_stability = pd.read_csv(
    SENS_DIR /
    "four_domain_pv_subspace_stability.csv"
)

axis_matching = pd.read_csv(
    SENS_DIR /
    "primary_to_expanded_axis_matching.csv"
)

axis_similarity = pd.read_csv(
    SENS_DIR /
    "primary_vs_expanded_axis_similarity.csv"
)

with open(
    SENS_DIR /
    "crest_final_sensitivity_findings_LOCKED.json",
    "r",
    encoding="utf-8"
) as f:
    sensitivity_locked = json.load(f)


print("=" * 120)
print("A. COMBINED-REPRESENTATION AXIS LOADINGS")
print("=" * 120)
print("Shape:", combined_loadings.shape)
print("Columns:", combined_loadings.columns.tolist())
display(combined_loadings)


print("\n" + "=" * 120)
print("B. COMBINED-REPRESENTATION PV STABILITY")
print("=" * 120)
print("Shape:", combined_pv_stability.shape)
print("Columns:", combined_pv_stability.columns.tolist())
display(combined_pv_stability)


print("\n" + "=" * 120)
print("C. BOTH-DIRECTION AXIS LOADINGS")
print("=" * 120)
print("Shape:", both_direction_loadings.shape)
print("Columns:", both_direction_loadings.columns.tolist())
display(both_direction_loadings)


print("\n" + "=" * 120)
print("D. BOTH-DIRECTION PV STABILITY")
print("=" * 120)
print("Shape:", both_direction_pv_stability.shape)
print("Columns:", both_direction_pv_stability.columns.tolist())
display(both_direction_pv_stability)


print("\n" + "=" * 120)
print("E. FOUR-DOMAIN EXPANDED AXIS LOADINGS")
print("=" * 120)
print("Shape:", four_domain_loadings.shape)
print("Columns:", four_domain_loadings.columns.tolist())
display(four_domain_loadings)


print("\n" + "=" * 120)
print("F. FOUR-DOMAIN PV SUBSPACE STABILITY")
print("=" * 120)
print("Shape:", four_domain_stability.shape)
print("Columns:", four_domain_stability.columns.tolist())
display(four_domain_stability)


print("\n" + "=" * 120)
print("G. PRIMARY-TO-EXPANDED AXIS MATCHING")
print("=" * 120)
print("Shape:", axis_matching.shape)
print("Columns:", axis_matching.columns.tolist())
display(axis_matching)


print("\n" + "=" * 120)
print("H. PRIMARY VS EXPANDED AXIS SIMILARITY")
print("=" * 120)
print("Shape:", axis_similarity.shape)
print("Columns:", axis_similarity.columns.tolist())
display(axis_similarity)


print("\n" + "=" * 120)
print("I. LOCKED FINAL SENSITIVITY FINDINGS")
print("=" * 120)

print(
    json.dumps(
        sensitivity_locked,
        indent=2,
        ensure_ascii=False
    )
)

In [ ]:
# Build Supplementary Table S9:
# Final sensitivity and robustness analyses

import json
import numpy as np
import pandas as pd

SENS_DIR = RESULTS_DIR / "final_sensitivity_robustness"
PROFILE_DIR = RESULTS_DIR / "crosssystem_profile_stability"

# Load locked sensitivity findings

with open(
    SENS_DIR / "crest_final_sensitivity_findings_LOCKED.json",
    "r",
    encoding="utf-8"
) as f:
    sensitivity_locked = json.load(f)

with open(
    PROFILE_DIR / "crest_crosssystem_profile_findings_LOCKED.json",
    "r",
    encoding="utf-8"
) as f:
    profile_locked = json.load(f)

four_domain_loadings = pd.read_csv(
    SENS_DIR / "four_domain_expanded_axis_loadings.csv"
)

axis_matching = pd.read_csv(
    SENS_DIR / "primary_to_expanded_axis_matching.csv"
)

# Extract locked results

combined = sensitivity_locked["combined_representation"]
both = sensitivity_locked["both_direction_complete_case"]
visual = sensitivity_locked["visual_domain_sensitivity"]

primary_n = int(
    profile_locked["primary_profile_cohort"]
)

# PANEL A - Robustness of the locked two-dimensional structure

panel_a = pd.DataFrame([
    {
        "Sensitivity analysis":
            "General + domain-specific representation",
        "N students": primary_n,
        "Dimension 1 cosine":
            combined["dimension_1_cosine"],
        "Dimension 2 cosine":
            combined["dimension_2_cosine"],
        "Rotation angle (deg)":
            combined["angle_degrees"],
        "Dimension 1 variance (%)":
            combined["variance_share_dimension_1_percent"],
        "Dimension 2 variance (%)":
            combined["variance_share_dimension_2_percent"],
    },
    {
        "Sensitivity analysis":
            "Both-direction complete-case cohort",
        "N students":
            both["n_students"],
        "Dimension 1 cosine":
            both["dimension_1_cosine"],
        "Dimension 2 cosine":
            both["dimension_2_cosine"],
        "Rotation angle (deg)":
            both["angle_degrees"],
        "Dimension 1 variance (%)":
            both["variance_share_dimension_1_percent"],
        "Dimension 2 variance (%)":
            both["variance_share_dimension_2_percent"],
    },
])

# PANEL B - Four-domain expanded profile space

variance_shares = visual[
    "expanded_variance_shares_percent"
]

panel_b = four_domain_loadings.copy()

panel_b = panel_b.rename(
    columns={
        "domain": "Domain",
        "expanded_dimension_1": "Expanded D1",
        "expanded_dimension_2": "Expanded D2",
        "expanded_dimension_3": "Expanded D3",
    }
)

# Add variance-share row separately when generating LaTeX

# PANEL C - Matching locked primary axes to four-domain axes

panel_c = axis_matching.copy()

panel_c = panel_c.rename(
    columns={
        "primary_dimension": "Primary dimension",
        "expanded_dimension": "Matched expanded dimension",
        "signed_cosine": "Signed cosine",
        "absolute_cosine": "Absolute cosine",
        "angle_degrees": "Angle (deg)",
    }
)

# Display

print("=" * 120)
print("SUPPLEMENTARY TABLE S9 - PANEL A")
print("=" * 120)

display(
    panel_a.round({
        "Dimension 1 cosine": 6,
        "Dimension 2 cosine": 6,
        "Rotation angle (deg)": 3,
        "Dimension 1 variance (%)": 2,
        "Dimension 2 variance (%)": 2,
    })
)

print("\n" + "=" * 120)
print("SUPPLEMENTARY TABLE S9 - PANEL B")
print("=" * 120)

display(
    panel_b.round({
        "Expanded D1": 6,
        "Expanded D2": 6,
        "Expanded D3": 6,
    })
)

print(
    "\nFour-domain complete N:",
    f"{visual['four_domain_complete_n']:,}"
)

print(
    "Four-domain coverage:",
    f"{visual['four_domain_coverage_percent']:.2f}%"
)

print(
    "Expanded variance shares:",
    ", ".join(
        f"{x:.2f}%"
        for x in variance_shares
    )
)

print("\n" + "=" * 120)
print("SUPPLEMENTARY TABLE S9 - PANEL C")
print("=" * 120)

display(
    panel_c.round({
        "Signed cosine": 6,
        "Absolute cosine": 6,
        "Angle (deg)": 3,
    })
)

# Integrity checks

print("\n" + "=" * 120)
print("INTEGRITY CHECKS")
print("=" * 120)

print(
    "Combined representation D1 cosine:",
    f"{combined['dimension_1_cosine']:.6f}"
)

print(
    "Combined representation D2 cosine:",
    f"{combined['dimension_2_cosine']:.6f}"
)

print(
    "Combined representation angle:",
    f"{combined['angle_degrees']:.3f} deg"
)

print(
    "Both-direction D1 cosine:",
    f"{both['dimension_1_cosine']:.6f}"
)

print(
    "Both-direction D2 cosine:",
    f"{both['dimension_2_cosine']:.6f}"
)

print(
    "Both-direction angle:",
    f"{both['angle_degrees']:.3f} deg"
)

print(
    "Primary D1 matched expanded dimension:",
    visual[
        "primary_dimension_1_matched_expanded_dimension"
    ]
)

print(
    "Primary D1 absolute cosine:",
    f"{visual['primary_dimension_1_absolute_cosine']:.6f}"
)

print(
    "Primary D2 matched expanded dimension:",
    visual[
        "primary_dimension_2_matched_expanded_dimension"
    ]
)

print(
    "Primary D2 absolute cosine:",
    f"{visual['primary_dimension_2_absolute_cosine']:.6f}"
)

print(
    "Additional Visual-related axis:",
    visual["additional_axis"]
)

print(
    "Additional axis Visual loading:",
    f"{visual['additional_axis_visual_loading']:.6f}"
)

# Verify axis-matching CSV against locked JSON
assert np.isclose(
    panel_c.loc[
        panel_c["Primary dimension"] == 1,
        "Absolute cosine"
    ].iloc[0],
    visual["primary_dimension_1_absolute_cosine"]
)

assert np.isclose(
    panel_c.loc[
        panel_c["Primary dimension"] == 2,
        "Absolute cosine"
    ].iloc[0],
    visual["primary_dimension_2_absolute_cosine"]
)

print("\nAxis matching reproduces locked findings: True")

# Save CSV outputs

panel_a_path = (
    SUPP_TABLE_DIR /
    "Table_S9A_primary_profile_robustness.csv"
)

panel_b_path = (
    SUPP_TABLE_DIR /
    "Table_S9B_four_domain_expansion.csv"
)

panel_c_path = (
    SUPP_TABLE_DIR /
    "Table_S9C_primary_axis_matching.csv"
)

panel_a.to_csv(panel_a_path, index=False)
panel_b.to_csv(panel_b_path, index=False)
panel_c.to_csv(panel_c_path, index=False)

# Generate LaTeX Table S9

latex_lines = []

latex_lines.append(r"\begin{table*}[t]")
latex_lines.append(
    r"\caption{Sensitivity analyses for the continuous "
    r"domain-relative CReST profile structure.}"
)
latex_lines.append(r"\label{tab:supp_profile_sensitivity}")
latex_lines.append(r"\centering")
latex_lines.append(r"\scriptsize")
latex_lines.append(r"\renewcommand{\arraystretch}{1.10}")
latex_lines.append("")

# Panel A

latex_lines.append(
    r"\textbf{Panel A. Robustness of the locked two-dimensional "
    r"profile structure}"
)
latex_lines.append(r"\par\smallskip")

latex_lines.append(
    r"\begin{tabular}{@{}lrrrrrr@{}}"
)

latex_lines.append(r"\toprule")

latex_lines.append(
    r"\textbf{Sensitivity analysis} & "
    r"\textbf{$N$} & "
    r"\textbf{D1 cosine} & "
    r"\textbf{D2 cosine} & "
    r"\textbf{Angle ($^\circ$)} & "
    r"\textbf{D1 variance (\%)} & "
    r"\textbf{D2 variance (\%)} \\"
)

latex_lines.append(r"\midrule")

for _, r in panel_a.iterrows():
    latex_lines.append(
        f"{r['Sensitivity analysis']} & "
        f"{int(r['N students']):,} & "
        f"{r['Dimension 1 cosine']:.6f} & "
        f"{r['Dimension 2 cosine']:.6f} & "
        f"{r['Rotation angle (deg)']:.3f} & "
        f"{r['Dimension 1 variance (%)']:.2f} & "
        f"{r['Dimension 2 variance (%)']:.2f} \\\\"
    )

latex_lines.append(r"\bottomrule")
latex_lines.append(r"\end{tabular}")

latex_lines.append(r"\vspace{1em}")

# Panel B

latex_lines.append(
    r"\textbf{Panel B. Four-domain expansion including Visual}"
)
latex_lines.append(r"\par\smallskip")

latex_lines.append(
    r"\begin{tabular}{@{}lrrr@{}}"
)

latex_lines.append(r"\toprule")

latex_lines.append(
    r"\textbf{Domain} & "
    r"\textbf{Expanded D1} & "
    r"\textbf{Expanded D2} & "
    r"\textbf{Expanded D3} \\"
)

latex_lines.append(r"\midrule")

for _, r in panel_b.iterrows():
    latex_lines.append(
        f"{r['Domain']} & "
        f"{r['Expanded D1']:+.4f} & "
        f"{r['Expanded D2']:+.4f} & "
        f"{r['Expanded D3']:+.4f} \\\\"
    )

latex_lines.append(r"\midrule")

latex_lines.append(
    f"Variance explained (\\%) & "
    f"{variance_shares[0]:.2f} & "
    f"{variance_shares[1]:.2f} & "
    f"{variance_shares[2]:.2f} \\\\"
)

latex_lines.append(r"\bottomrule")
latex_lines.append(r"\end{tabular}")

latex_lines.append(r"\vspace{0.4em}")

latex_lines.append(
    r"\parbox{0.90\textwidth}{\footnotesize "
    f"Four-domain complete-case cohort: "
    f"$N={visual['four_domain_complete_n']:,}$ "
    f"({visual['four_domain_coverage_percent']:.2f}\\% "
    r"of the primary scorable cohort).}"
)

latex_lines.append(r"\vspace{1em}")

# Panel C

latex_lines.append(
    r"\textbf{Panel C. Matching of the locked primary axes "
    r"within the four-domain expanded space}"
)
latex_lines.append(r"\par\smallskip")

latex_lines.append(
    r"\begin{tabular}{@{}crrr@{}}"
)

latex_lines.append(r"\toprule")

latex_lines.append(
    r"\textbf{Primary dimension} & "
    r"\textbf{Matched expanded dimension} & "
    r"\textbf{$|\cos(\theta)|$} & "
    r"\textbf{Angle ($^\circ$)} \\"
)

latex_lines.append(r"\midrule")

for _, r in panel_c.iterrows():
    latex_lines.append(
        f"{int(r['Primary dimension'])} & "
        f"{int(r['Matched expanded dimension'])} & "
        f"{r['Absolute cosine']:.6f} & "
        f"{r['Angle (deg)']:.3f} \\\\"
    )

latex_lines.append(r"\bottomrule")
latex_lines.append(r"\end{tabular}")

# Note

latex_lines.append("")
latex_lines.append(
    r"\begin{flushleft}"
    r"\footnotesize "
    r"\textit{Note.} Cosine similarities compare sensitivity-analysis "
    r"axes with the locked primary Written--Social--Scientific profile "
    r"axes. Adding the general creative representation to the "
    r"domain-specific representation left the two-dimensional structure "
    r"essentially unchanged ($|\cos(\theta)|=0.999245$, "
    r"rotation $=2.23^\circ$). Requiring complete availability in both "
    r"disjoint-item directions retained the same qualitative structure "
    r"in 52,684 students, with moderate rotation "
    r"($|\cos(\theta)|=0.986374$, $9.47^\circ$). "
    r"When Visual was added, the leading expanded dimension was strongly "
    r"Visual-related (loading $=0.8652$) and explained 47.05\% of the "
    r"expanded non-zero variance. This changed the eigenvalue ordering "
    r"rather than eliminating the locked primary structure: primary "
    r"Dimension 1 reappeared as expanded Dimension 2 "
    r"($|\cos(\theta)|=0.999472$), and primary Dimension 2 reappeared "
    r"as expanded Dimension 3 ($|\cos(\theta)|=0.998536$). "
    r"Accordingly, Visual expands rather than invalidates the primary "
    r"domain-relative profile space. Because Visual was represented by "
    r"only four Creative Thinking items and had lower effective coverage, "
    r"the three-domain Written--Social--Scientific structure remains the "
    r"primary profile analysis."
    r"\end{flushleft}"
)

latex_lines.append(r"\end{table*}")

latex_text = "\n".join(latex_lines)

tex_path = (
    SUPP_TABLE_DIR /
    "Table_S9_final_profile_sensitivity.tex"
)

tex_path.write_text(
    latex_text,
    encoding="utf-8"
)

print("\nSaved:")
print(panel_a_path)
print(panel_b_path)
print(panel_c_path)
print(tex_path)

print("\n" + "=" * 120)
print("LATEX PREVIEW")
print("=" * 120)
print(latex_text)

========================================================================================================================
SUPPLEMENTARY TABLE S9 - PANEL A
========================================================================================================================

,Sensitivity analysis,N students,Dimension 1 cosine,Dimension 2 cosine,Rotation angle (deg),Dimension 1 variance (%),Dimension 2 variance (%)
0,General + domain-specific representation,139894,0.999245,0.999245,2.226,69.69,30.31
1,Both-direction complete-case cohort,52684,0.986374,0.986374,9.469,78.93,21.07

========================================================================================================================
SUPPLEMENTARY TABLE S9 - PANEL B
========================================================================================================================

       Domain  Expanded D1  Expanded D2  Expanded D3
0     Written    -0.255302     0.283461    -0.777477
1      Social    -0.294211    -0.804916     0.124699
2  Scientific    -0.315700     0.521306     0.615283
3      Visual     0.865213     0.000150     0.037495

Four-domain complete N: 94,815
Four-domain coverage: 66.51%
Expanded variance shares: 47.05%, 37.25%, 15.70%

========================================================================================================================
SUPPLEMENTARY TABLE S9 - PANEL C
========================================================================================================================

   Primary dimension  Matched expanded dimension  Signed cosine  Absolute cosine  Angle (deg)
0                  1                           2      -0.999472         0.999472        1.861
1                  2                           3       0.998536         0.998536        3.101

========================================================================================================================
INTEGRITY CHECKS
========================================================================================================================
Combined representation D1 cosine: 0.999245
Combined representation D2 cosine: 0.999245
Combined representation angle: 2.226 deg
Both-direction D1 cosine: 0.986374
Both-direction D2 cosine: 0.986374
Both-direction angle: 9.469 deg
Primary D1 matched expanded dimension: 2
Primary D1 absolute cosine: 0.999472
Primary D2 matched expanded dimension: 3
Primary D2 absolute cosine: 0.998536
Additional Visual-related axis: 1
Additional axis Visual loading: 0.865213

Axis matching reproduces locked findings: True

Saved:
PROJECT_ROOT\results\supplementary_material\tables\Table_S9A_primary_profile_robustness.csv
PROJECT_ROOT\results\supplementary_material\tables\Table_S9B_four_domain_expansion.csv
PROJECT_ROOT\results\supplementary_material\tables\Table_S9C_primary_axis_matching.csv
PROJECT_ROOT\results\supplementary_material\tables\Table_S9_final_profile_sensitivity.tex

========================================================================================================================
LATEX PREVIEW
========================================================================================================================
\begin{table*}[t]
\caption{Sensitivity analyses for the continuous domain-relative CReST profile structure.}
\label{tab:supp_profile_sensitivity}
\centering
\scriptsize
\renewcommand{\arraystretch}{1.10}

\textbf{Panel A. Robustness of the locked two-dimensional profile structure}
\par\smallskip
\begin{tabular}{@{}lrrrrrr@{}}
\toprule
\textbf{Sensitivity analysis} & \textbf{$N$} & \textbf{D1 cosine} & \textbf{D2 cosine} & \textbf{Angle ($^\circ$)} & \textbf{D1 variance (\%)} & \textbf{D2 variance (\%)} \\
\midrule
General + domain-specific representation & 139,894 & 0.999245 & 0.999245 & 2.226 & 69.69 & 30.31 \\
Both-direction complete-case cohort & 52,684 & 0.986374 & 0.986374 & 9.469 & 78.93 & 21.07 \\
\bottomrule
\end{tabular}
\vspace{1em}
\textbf{Panel B. Four-domain expansion including Visual}
\par\smallskip
\begin{tabular}{@{}lrrr@{}}
\toprule
\textbf{Domain} & \textbf{Expanded D1} & \textbf{Expanded D2} & \textbf{Expanded D3} \\
\midrule
Written & -0.2553 & +0.2835 & -0.7775 \\
Social & -0.2942 & -0.8049 & +0.1247 \\
Scientific & -0.3157 & +0.5213 & +0.6153 \\
Visual & +0.8652 & +0.0001 & +0.0375 \\
\midrule
Variance explained (\%) & 47.05 & 37.25 & 15.70 \\
\bottomrule
\end{tabular}
\vspace{0.4em}
\parbox{0.90\textwidth}{\footnotesize Four-domain complete-case cohort: $N=94,815$ (66.51\% of the primary scorable cohort).}
\vspace{1em}
\textbf{Panel C. Matching of the locked primary axes within the four-domain expanded space}
\par\smallskip
\begin{tabular}{@{}crrr@{}}
\toprule
\textbf{Primary dimension} & \textbf{Matched expanded dimension} & \textbf{$|\cos(\theta)|$} & \textbf{Angle ($^\circ$)} \\
\midrule
1 & 2 & 0.999472 & 1.861 \\
2 & 3 & 0.998536 & 3.101 \\
\bottomrule
\end{tabular}

\begin{flushleft}\footnotesize \textit{Note.} Cosine similarities compare sensitivity-analysis axes with the locked primary Written--Social--Scientific profile axes. Adding the general creative representation to the domain-specific representation left the two-dimensional structure essentially unchanged ($|\cos(\theta)|=0.999245$, rotation $=2.23^\circ$). Requiring complete availability in both disjoint-item directions retained the same qualitative structure in 52,684 students, with moderate rotation ($|\cos(\theta)|=0.986374$, $9.47^\circ$). When Visual was added, the leading expanded dimension was strongly Visual-related (loading $=0.8652$) and explained 47.05\% of the expanded non-zero variance. This changed the eigenvalue ordering rather than eliminating the locked primary structure: primary Dimension 1 reappeared as expanded Dimension 2 ($|\cos(\theta)|=0.999472$), and primary Dimension 2 reappeared as expanded Dimension 3 ($|\cos(\theta)|=0.998536$). Accordingly, Visual expands rather than invalidates the primary domain-relative profile space. Because Visual was represented by only four Creative Thinking items and had lower effective coverage, the three-domain Written--Social--Scientific structure remains the primary profile analysis.\end{flushleft}
\end{table*}

In [ ]:
from pathlib import Path
import shutil

figure_specs = [
    ("S1", FIG_DIR / "fig_fold0_pretraining_curve.pdf",
     SUPP_FIG_DIR / "Figure_S1_fold0_pretraining_curve.pdf"),
    ("S2", FIG_DIR / "fig_fold0_latent_routing.pdf",
     SUPP_FIG_DIR / "Figure_S2_fold0_latent_routing.pdf"),
    ("S3", FIG_DIR / "fig_country_domain_official_heatmap.pdf",
     SUPP_FIG_DIR / "Figure_S3_country_domain_official_heatmap.pdf"),
    ("S4", FIG_DIR / "fig_country_domain_support_sensitivity.pdf",
     SUPP_FIG_DIR / "Figure_S4_country_domain_support_sensitivity.pdf"),
]

for number, source, target in figure_specs:
    assert source.exists(), f"Missing figure: {source}"
    shutil.copy2(source, target)

print(f"Prepared {len(figure_specs)} Supplementary figures.")

In [ ]:
master_tex = r"""
\documentclass[11pt]{article}

\usepackage[a4paper,margin=2.2cm]{geometry}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{array}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{caption}
\usepackage{float}
\usepackage{microtype}
\usepackage[hidelinks]{hyperref}
\usepackage{placeins}

\renewcommand{\thetable}{S\arabic{table}}
\renewcommand{\thefigure}{S\arabic{figure}}

\setlength{\parindent}{0pt}
\setlength{\parskip}{5pt}

\title{
\textbf{Supplementary Material}\\[0.5em]
Beyond Overall Proficiency: CReST Reveals Domain-Relative Structure
in Creative Thinking Across Education Systems
}
\author{
Kubra Kirca Demirbaga
\and
Umit Demirbaga
}
\date{}

\begin{document}
\maketitle

\section*{Overview}
This Supplementary Material provides additional information on the
cross-system experimental design, computational audit, development-stage
diagnostics, assessment-design calibration, nuisance robustness,
domain- and process-specific analyses, survey-weighted contextual
associations, alignment with official PISA 2022 Creative Thinking
proficiency, the stability and sensitivity of the continuous
domain-relative creative-performance profile identified by CReST, and
cross-system domain-profile sensitivity.

The analyses use the same locked modelling pipeline and outer
cross-system evaluation design reported in the main manuscript.
Development-stage diagnostics are explicitly identified as such and
were not used to revise models after inspection of held-out outer-fold
test results.

\section*{S1. Cross-System Experimental Design}
The final evaluation used seven outer folds. Each of the 63 education
systems served exactly once as an unseen test system and exactly once
as a validation system. For any given outer fold, the remaining 45
systems constituted the training set. Table~\ref{tab:supp_split_assignment}
summarises the seven-fold split design and corresponding sample sizes.

\input{tables/Table_S1_seven_fold_system_assignment.tex}
\FloatBarrier

\section*{S2. Computational and Development-Stage Diagnostics}
Table~\ref{tab:supp_computational_audit} summarises training and
inference characteristics across the seven final outer folds. Figures
\ref{fig:supp_fold0_pretraining} and \ref{fig:supp_fold0_latent_routing}
provide development-stage Fold~0 diagnostics.

\input{tables/Table_S2_fold_level_computational_audit.tex}

\begin{figure}[H]
\centering
\includegraphics[width=0.90\textwidth]{figures/Figure_S1_fold0_pretraining_curve.pdf}
\caption{Development-stage Fold~0 reconstruction learning curve. Training
reconstruction and country-equal validation reconstruction are shown
across epochs, with the selected development-stage checkpoint marked at
epoch 19. This figure documents model development and is distinct from
the final locked seven-fold training runs reported in
Table~\ref{tab:supp_computational_audit}, for which the Fold~0 checkpoint
was selected at epoch 18.}
\label{fig:supp_fold0_pretraining}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=0.90\textwidth]{figures/Figure_S2_fold0_latent_routing.pdf}
\caption{Development-stage Fold~0 latent-routing diagnostics across
training. Curves show cross-entropy losses for predicting country from
the context latent, country from the creative latent through a
gradient-reversal layer (GRL), and booklet from the creative latent
through a GRL. Horizontal reference lines indicate equal-probability
cross-entropy levels for 45 training countries and 30 booklets.}
\label{fig:supp_fold0_latent_routing}
\end{figure}
\FloatBarrier

\section*{S3. Assessment-Design Calibration and Nuisance Robustness}
The assessment-design calibration procedure was developed using
training data before confirmatory access to the outer-fold test systems.
Table~\ref{tab:supp_design_calibration} reports calibration results and
Table~\ref{tab:supp_nuisance_probes} reports final nuisance probes.

\input{tables/Table_S3_design_calibration_and_signal_retention.tex}
\input{tables/Table_S4_final_crosssystem_nuisance_probes.tex}
\FloatBarrier

\section*{S4. Domain- and Process-Specific Incremental Information}
Table~\ref{tab:supp_domain_process_increment} reports incremental
information associated with domain-specific and process-anchored
representations.

\input{tables/Table_S5_domain_process_increment.tex}
\FloatBarrier

\section*{S5. Survey-Weighted Contextual Associations}
Table~\ref{tab:supp_context_associations} reports survey-weighted
contextual associations with the CReST disjoint-item transfer score.
These analyses are descriptive rather than causal.

\input{tables/Table_S6_context_associations.tex}
\FloatBarrier

\section*{S6. Alignment with Official PISA Creative Thinking Proficiency}
Table~\ref{tab:supp_pisa_alignment} evaluates convergent alignment
between the CReST transfer score and official PISA 2022 Creative
Thinking proficiency represented by all ten plausible values. Because
both quantities originate from the same assessment, this is interpreted
as convergent alignment rather than external validation.

\input{tables/Table_S7_pisa_ct_convergent_alignment.tex}
\FloatBarrier

\section*{S7. Continuous Profile Structure and Clustering Safeguard}
Table~\ref{tab:supp_profile_structure} evaluates continuous profile
structure, clustering safeguards, and axis stability.

\input{tables/Table_S8_profile_structure_and_stability.tex}
\FloatBarrier

\section*{S8. Profile Sensitivity and Visual-Domain Expansion}
Table~\ref{tab:supp_profile_sensitivity} reports final profile
sensitivity analyses, including the Visual-domain expansion.

\input{tables/Table_S9_final_profile_sensitivity.tex}
\FloatBarrier

\section*{S9. Cross-System Domain Profiles and Support Sensitivity}
Figure~\ref{fig:supp_country_domain_heatmap} displays survey-weighted
full-credit profiles across Written, Visual, Social, and Scientific
domains. Figure~\ref{fig:supp_country_domain_support} evaluates
sensitivity to cross-system item support.

\begin{figure}[H]
\centering
\includegraphics[width=0.60\textwidth]{figures/Figure_S3_country_domain_official_heatmap.pdf}
\caption{PISA 2022 Creative Thinking domain profiles across education
systems using the official 32-item profile. Cells show weighted
full-credit rates for Written, Visual, Social, and Scientific domains.
Education systems are ordered by their mean full-credit rate across the
four domains.}
\label{fig:supp_country_domain_heatmap}
\end{figure}

\begin{figure}[H]
\centering
\includegraphics[width=0.60\textwidth]{figures/Figure_S4_country_domain_support_sensitivity.pdf}
\caption{Sensitivity of education-system domain profiles to cross-system
item support. Each cell shows the common-support full-credit rate minus
the corresponding official-profile full-credit rate. Positive values
indicate a higher estimate under the common-support restriction and
negative values indicate a lower estimate. Education systems follow the
same ordering as Figure~\ref{fig:supp_country_domain_heatmap}.}
\label{fig:supp_country_domain_support}
\end{figure}
\FloatBarrier

\end{document}
"""

master_path = SUPP_DIR / "supplementary_material.tex"
master_path.write_text(master_tex.strip() + "\n", encoding="utf-8")
print("Saved:", master_path)

In [ ]:
import re
from collections import Counter

master_path = SUPP_DIR / "supplementary_material.tex"
tex_files = [master_path] + sorted(SUPP_TABLE_DIR.glob("*.tex"))

label_pattern = re.compile(r"\\label\{([^}]+)\}")
ref_pattern = re.compile(r"\\(?:ref|pageref|autoref)\{([^}]+)\}")

labels = []
refs = []

for path in tex_files:
    text = path.read_text(encoding="utf-8", errors="ignore")
    labels.extend(label_pattern.findall(text))
    refs.extend(ref_pattern.findall(text))

missing_refs = sorted(set(refs) - set(labels))
duplicate_labels = sorted(
    label for label, count in Counter(labels).items() if count > 1
)

master_text = master_path.read_text(encoding="utf-8")
input_paths = re.findall(r"\\input\{([^}]+)\}", master_text)
missing_inputs = []

for rel in input_paths:
    path = SUPP_DIR / rel
    if path.suffix == "":
        path = path.with_suffix(".tex")
    if not path.exists():
        missing_inputs.append(rel)

missing_figures = [
    target.name
    for _, _, target in figure_specs
    if not target.exists()
]

assert not missing_refs, f"Missing references: {missing_refs}"
assert not duplicate_labels, f"Duplicate labels: {duplicate_labels}"
assert not missing_inputs, f"Missing table inputs: {missing_inputs}"
assert not missing_figures, f"Missing figures: {missing_figures}"

print("Supplementary Material structural audit: PASS")